[functions.founder-onboarding]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.stripe-checkout]
verify_jwt = true

[functions.stripe-cancel]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
