[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://ehjvkbpjwedtgtpufpyz.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoanZrYnBqd2VkdGd0cHVmcHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU1MzkzNzIsImV4cCI6MjEwMTExNTM3Mn0.pO3FiHPxK2vxGX18NLOnwFVlMvxFOwQr-Z72OKYBdsI"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
