import type { MarketListing, MarketEvent, CommunityFeedItem } from './types';

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysFromNow = (d: number) => {
  const dt = new Date(now);
  dt.setDate(dt.getDate() + d);
  return dt.toISOString().split('T')[0];
};

export const PLACEHOLDER_LISTINGS: MarketListing[] = [
  {
    id: 'ph-listing-1',
    owner_id: '',
    city_id: '',
    name: 'Crown & Co. Barbershop',
    category: 'services',
    description: 'Precision fades, hot towel shaves, and classic cuts in a welcoming atmosphere. Walking appointments available.',
    products_services: 'Fades, tapers, beard grooming, hot towel shaves, kids cuts',
    price_display: '$25–$45',
    external_url: '',
    contact_info: '(555) 123-4567',
    image_url: null,
    status: 'approved',
    is_verified: true,
    like_count: 142,
    comment_count: 38,
    check_in_count: 89,
    created_at: hoursAgo(120),
    updated_at: hoursAgo(12),
    rank_score: 95,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-2',
    owner_id: '',
    city_id: '',
    name: 'Sankofa Soul Food Kitchen',
    category: 'products',
    description: 'Family recipes passed down three generations. Catering, meal prep, and weekend pop-ups serving the neighborhood.',
    products_services: 'Catering, meal prep, weekend pop-up dinners, soul food plates',
    price_display: '$12–$200',
    external_url: '',
    contact_info: 'hello@sankofakitchen.com',
    image_url: null,
    status: 'approved',
    is_verified: true,
    like_count: 218,
    comment_count: 54,
    check_in_count: 156,
    created_at: hoursAgo(96),
    updated_at: hoursAgo(6),
    rank_score: 92,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-3',
    owner_id: '',
    city_id: '',
    name: 'Melanin Wealth Financial Planning',
    category: 'services',
    description: 'Comprehensive financial planning, debt elimination strategies, and investment guidance tailored to our community.',
    products_services: 'Financial planning, debt elimination, investment advising, retirement planning',
    price_display: 'Free consult',
    external_url: '',
    contact_info: '(555) 987-6543',
    image_url: null,
    status: 'approved',
    is_verified: true,
    like_count: 97,
    comment_count: 23,
    check_in_count: 41,
    created_at: hoursAgo(72),
    updated_at: hoursAgo(24),
    rank_score: 88,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-4',
    owner_id: '',
    city_id: '',
    name: 'Nubian Naturals Hair Care',
    category: 'products',
    description: 'Handcrafted natural hair products made with shea butter, black soap, and essential oils. No sulfates, no parabens.',
    products_services: 'Shampoos, conditioners, hair oils, edge control, curl creams, beard oils',
    price_display: '$8–$32',
    external_url: '',
    contact_info: 'orders@nubiannaturals.com',
    image_url: null,
    status: 'approved',
    is_verified: false,
    like_count: 76,
    comment_count: 15,
    check_in_count: 28,
    created_at: hoursAgo(48),
    updated_at: hoursAgo(18),
    rank_score: 81,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-5',
    owner_id: '',
    city_id: '',
    name: 'The Village Print & Design Co.',
    category: 'services',
    description: 'Custom apparel printing, business branding, and graphic design. From concept to delivery, we build your brand.',
    products_services: 'Screen printing, embroidery, logo design, business cards, flyers',
    price_display: '$20+',
    external_url: '',
    contact_info: '(555) 456-7890',
    image_url: null,
    status: 'approved',
    is_verified: true,
    like_count: 64,
    comment_count: 12,
    check_in_count: 33,
    created_at: hoursAgo(36),
    updated_at: hoursAgo(8),
    rank_score: 79,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-6',
    owner_id: '',
    city_id: '',
    name: 'Brickhouse Fitness Studio',
    category: 'services',
    description: 'Group fitness, personal training, and wellness coaching. All levels welcome. Your goals, our mission.',
    products_services: 'Personal training, group classes, nutrition coaching, wellness programs',
    price_display: '$15/class',
    external_url: '',
    contact_info: 'fit@brickhousestudio.com',
    image_url: null,
    status: 'approved',
    is_verified: false,
    like_count: 53,
    comment_count: 9,
    check_in_count: 67,
    created_at: hoursAgo(24),
    updated_at: hoursAgo(4),
    rank_score: 74,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-7',
    owner_id: '',
    city_id: '',
    name: 'Sweet Auburn Bakery',
    category: 'products',
    description: 'Southern-style baked goods made fresh daily. Sweet potato pies, peach cobblers, and custom cakes for every occasion.',
    products_services: 'Custom cakes, pies, cobblers, cookies, catering desserts',
    price_display: '$5–$75',
    external_url: '',
    contact_info: '(555) 234-5678',
    image_url: null,
    status: 'approved',
    is_verified: true,
    like_count: 131,
    comment_count: 31,
    check_in_count: 72,
    created_at: hoursAgo(18),
    updated_at: hoursAgo(2),
    rank_score: 71,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
  {
    id: 'ph-listing-8',
    owner_id: '',
    city_id: '',
    name: 'Harambe Legal Services',
    category: 'services',
    description: 'Affordable legal help for small businesses, contracts, and estate planning. Justice is not a luxury.',
    products_services: 'Business formation, contract review, estate planning, trademark filing',
    price_display: 'Consult $75',
    external_url: '',
    contact_info: 'legal@harambeservices.com',
    image_url: null,
    status: 'approved',
    is_verified: true,
    like_count: 42,
    comment_count: 7,
    check_in_count: 19,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(1),
    rank_score: 68,
    city_name: 'Atlanta',
    city_state: 'GA',
  },
];

export const PLACEHOLDER_EVENTS: MarketEvent[] = [
  {
    id: 'ph-event-1',
    author_id: '',
    city_id: '',
    listing_id: 'ph-listing-1',
    name: 'Free Back-to-School Haircuts for Kids',
    description: 'Community day! Free haircuts for school-age children. First come, first served. Snacks and music provided.',
    event_date: daysFromNow(3),
    event_time: '10:00 AM',
    location_text: 'Crown & Co. Barbershop, 123 Auburn Ave',
    external_url: '',
    image_url: null,
    status: 'approved',
    check_in_count: 34,
    created_at: hoursAgo(48),
    updated_at: hoursAgo(48),
    listing_name: 'Crown & Co. Barbershop',
  },
  {
    id: 'ph-event-2',
    author_id: '',
    city_id: '',
    listing_id: 'ph-listing-2',
    name: 'Soul Food Sunday Pop-Up Dinner',
    description: 'Join us for a three-course soul food experience. Seating limited to 40 guests. Tickets at the door.',
    event_date: daysFromNow(6),
    event_time: '5:00 PM',
    location_text: 'Sweet Auburn Market, 232 Edgewood Ave',
    external_url: '',
    image_url: null,
    status: 'approved',
    check_in_count: 51,
    created_at: hoursAgo(36),
    updated_at: hoursAgo(36),
    listing_name: 'Sankofa Soul Food Kitchen',
  },
  {
    id: 'ph-event-3',
    author_id: '',
    city_id: '',
    listing_id: null,
    name: 'Black Business Owners Networking Mixer',
    description: 'Connect with fellow entrepreneurs, share resources, and build partnerships. Light refreshments served.',
    event_date: daysFromNow(10),
    event_time: '6:30 PM',
    location_text: 'The Village Community Center, 455 Cascade Rd',
    external_url: '',
    image_url: null,
    status: 'approved',
    check_in_count: 28,
    created_at: hoursAgo(24),
    updated_at: hoursAgo(24),
    listing_name: undefined,
  },
  {
    id: 'ph-event-4',
    author_id: '',
    city_id: '',
    listing_id: 'ph-listing-6',
    name: 'Outdoor Boot Camp Challenge',
    description: 'All-levels outdoor workout in the park. Bring water and a mat. Free for first-timers.',
    event_date: daysFromNow(14),
    event_time: '8:00 AM',
    location_text: 'Grant Park, Pavilion 3',
    external_url: '',
    image_url: null,
    status: 'approved',
    check_in_count: 16,
    created_at: hoursAgo(12),
    updated_at: hoursAgo(12),
    listing_name: 'Brickhouse Fitness Studio',
  },
];

export const PLACEHOLDER_FEED: CommunityFeedItem[] = [
  {
    id: 'ph-feed-1',
    feed_type: 'update',
    listing_id: 'ph-listing-2',
    listing_name: 'Sankofa Soul Food Kitchen',
    city_id: '',
    body: 'We are now taking pre-orders for Thanksgiving! Sweet potato pies, collard green platters, and full holiday catering packages. Call or message us to reserve yours before we sell out.',
    image_url: null,
    author_id: '',
    created_at: hoursAgo(3),
    rank_score: 0,
  },
  {
    id: 'ph-feed-2',
    feed_type: 'update',
    listing_id: 'ph-listing-4',
    listing_name: 'Nubian Naturals Hair Care',
    city_id: '',
    body: 'New product drop! Our hibiscus-infused curl defining cream is now available online and in-store. Made fresh this week with organic ingredients.',
    image_url: null,
    author_id: '',
    created_at: hoursAgo(8),
    rank_score: 0,
  },
  {
    id: 'ph-feed-3',
    feed_type: 'update',
    listing_id: 'ph-listing-1',
    listing_name: 'Crown & Co. Barbershop',
    city_id: '',
    body: 'Extended hours this weekend! Open Saturday and Sunday from 8 AM to 8 PM. Walk-ins welcome, or book ahead to skip the wait.',
    image_url: null,
    author_id: '',
    created_at: hoursAgo(14),
    rank_score: 0,
  },
  {
    id: 'ph-feed-4',
    feed_type: 'event',
    listing_id: 'ph-listing-1',
    listing_name: 'Free Back-to-School Haircuts for Kids',
    city_id: '',
    body: 'Community day! Free haircuts for school-age children this Saturday. First come, first served. Snacks and music provided. Come support our youth.',
    image_url: null,
    author_id: '',
    created_at: hoursAgo(48),
    rank_score: 0,
  },
  {
    id: 'ph-feed-5',
    feed_type: 'event',
    listing_id: null,
    listing_name: 'Black Business Owners Networking Mixer',
    city_id: '',
    body: 'Connect with fellow entrepreneurs, share resources, and build partnerships. Light refreshments served. RSVP encouraged but not required.',
    image_url: null,
    author_id: '',
    created_at: hoursAgo(24),
    rank_score: 0,
  },
];
