/*
# Seed Major US Cities Across All 50 States

## Purpose
Populates the cities table with hundreds of real US cities across all 50 states
so that city autocomplete works for any state the user selects.

## Approach
- Inserts cities grouped by state with real city names
- Assigns metro_id where a matching metro exists (Atlanta Metro, Chicago Metro, etc.)
- All new cities start at 'settlement' tier with 0 founders
- Uses ON CONFLICT (slug) DO NOTHING to be idempotent

## Security
This migration only inserts data — no schema or policy changes.
*/

-- Helper: insert a city with optional metro assignment
-- We use a CTE pattern to look up metro_id by metro name + state abbreviation

-- ==================== SEED CITIES ====================
INSERT INTO cities (name, slug, state, tier, founder_count, metro_id)
SELECT v.name, v.slug, v.state, 'settlement', 0, m.id
FROM (VALUES
  -- Alabama
  ('Birmingham', 'birmingham-al', 'AL'),
  ('Montgomery', 'montgomery-al', 'AL'),
  ('Mobile', 'mobile-al', 'AL'),
  ('Huntsville', 'huntsville-al', 'AL'),
  ('Tuscaloosa', 'tuscaloosa-al', 'AL'),
  ('Hoover', 'hoover-al', 'AL'),
  ('Dothan', 'dothan-al', 'AL'),
  ('Auburn', 'auburn-al', 'AL'),
  ('Decatur', 'decatur-al', 'AL'),
  ('Madison', 'madison-al', 'AL'),
  ('Florence', 'florence-al', 'AL'),
  ('Gadsden', 'gadsden-al', 'AL'),
  ('Phenix City', 'phenix-city-al', 'AL'),
  ('Prichard', 'prichard-al', 'AL'),
  ('Opelika', 'opelika-al', 'AL'),
  -- Alaska
  ('Anchorage', 'anchorage-ak', 'AK'),
  ('Fairbanks', 'fairbanks-ak', 'AK'),
  ('Juneau', 'juneau-ak', 'AK'),
  ('Sitka', 'sitka-ak', 'AK'),
  ('Ketchikan', 'ketchikan-ak', 'AK'),
  ('Wasilla', 'wasilla-ak', 'AK'),
  ('Kenai', 'kenai-ak', 'AK'),
  ('Kodiak', 'kodiak-ak', 'AK'),
  ('Bethel', 'bethel-ak', 'AK'),
  ('Palmer', 'palmer-ak', 'AK'),
  -- Arizona
  ('Phoenix', 'phoenix', 'AZ'),
  ('Tucson', 'tucson-az', 'AZ'),
  ('Mesa', 'mesa-az', 'AZ'),
  ('Chandler', 'chandler-az', 'AZ'),
  ('Scottsdale', 'scottsdale-az', 'AZ'),
  ('Glendale', 'glendale-az', 'AZ'),
  ('Gilbert', 'gilbert-az', 'AZ'),
  ('Tempe', 'tempe-az', 'AZ'),
  ('Peoria', 'peoria-az', 'AZ'),
  ('Surprise', 'surprise-az', 'AZ'),
  ('Yuma', 'yuma-az', 'AZ'),
  ('Flagstaff', 'flagstaff-az', 'AZ'),
  ('Goodyear', 'goodyear-az', 'AZ'),
  ('Lake Havasu City', 'lake-havasu-city-az', 'AZ'),
  ('Buckeye', 'buckeye-az', 'AZ'),
  ('Prescott', 'prescott-az', 'AZ'),
  ('Casa Grande', 'casa-grande-az', 'AZ'),
  ('Maricopa', 'maricopa-az', 'AZ'),
  ('Sierra Vista', 'sierra-vista-az', 'AZ'),
  -- Arkansas
  ('Little Rock', 'little-rock-ar', 'AR'),
  ('Fort Smith', 'fort-smith-ar', 'AR'),
  ('Fayetteville', 'fayetteville-ar', 'AR'),
  ('Springdale', 'springdale-ar', 'AR'),
  ('Jonesboro', 'jonesboro-ar', 'AR'),
  ('Conway', 'conway-ar', 'AR'),
  ('Rogers', 'rogers-ar', 'AR'),
  ('Bentonville', 'bentonville-ar', 'AR'),
  ('Pine Bluff', 'pine-bluff-ar', 'AR'),
  ('Hot Springs', 'hot-springs-ar', 'AR'),
  ('Texarkana', 'texarkana-ar', 'AR'),
  ('Benton', 'benton-ar', 'AR'),
  ('Van Buren', 'van-buren-ar', 'AR'),
  ('Searcy', 'searcy-ar', 'AR'),
  -- California
  ('Los Angeles', 'los-angeles', 'CA'),
  ('San Diego', 'san-diego-ca', 'CA'),
  ('San Jose', 'san-jose-ca', 'CA'),
  ('San Francisco', 'san-francisco-ca', 'CA'),
  ('Fresno', 'fresno-ca', 'CA'),
  ('Sacramento', 'sacramento-ca', 'CA'),
  ('Long Beach', 'long-beach-ca', 'CA'),
  ('Oakland', 'oakland-ca', 'CA'),
  ('Bakersfield', 'bakersfield-ca', 'CA'),
  ('Anaheim', 'anaheim-ca', 'CA'),
  ('Santa Ana', 'santa-ana-ca', 'CA'),
  ('Riverside', 'riverside-ca', 'CA'),
  ('Stockton', 'stockton-ca', 'CA'),
  ('Irvine', 'irvine-ca', 'CA'),
  ('Chula Vista', 'chula-vista-ca', 'CA'),
  ('Fremont', 'fremont-ca', 'CA'),
  ('San Bernardino', 'san-bernardino-ca', 'CA'),
  ('Modesto', 'modesto-ca', 'CA'),
  ('Oxnard', 'oxnard-ca', 'CA'),
  ('Fontana', 'fontana-ca', 'CA'),
  ('Moreno Valley', 'moreno-valley-ca', 'CA'),
  ('Glendale', 'glendale-ca', 'CA'),
  ('Huntington Beach', 'huntington-beach-ca', 'CA'),
  ('Santa Clarita', 'santa-clarita-ca', 'CA'),
  ('Garden Grove', 'garden-grove-ca', 'CA'),
  ('Santa Rosa', 'santa-rosa-ca', 'CA'),
  ('Oceanside', 'oceanside-ca', 'CA'),
  ('Rancho Cucamonga', 'rancho-cucamonga-ca', 'CA'),
  ('Ontario', 'ontario-ca', 'CA'),
  ('Santa Barbara', 'santa-barbara-ca', 'CA'),
  ('Pomona', 'pomona-ca', 'CA'),
  ('Elk Grove', 'elk-grove-ca', 'CA'),
  ('Corona', 'corona-ca', 'CA'),
  ('Lancaster', 'lancaster-ca', 'CA'),
  ('Palmdale', 'palmdale-ca', 'CA'),
  ('Salinas', 'salinas-ca', 'CA'),
  ('Hayward', 'hayward-ca', 'CA'),
  ('Perris', 'perris-ca', 'CA'),
  ('Sunnyvale', 'sunnyvale-ca', 'CA'),
  ('Torrance', 'torrance-ca', 'CA'),
  ('Pasadena', 'pasadena-ca', 'CA'),
  ('Escondido', 'escondido-ca', 'CA'),
  ('Orange', 'orange-ca', 'CA'),
  ('Fullerton', 'fullerton-ca', 'CA'),
  ('Thousand Oaks', 'thousand-oaks-ca', 'CA'),
  ('Visalia', 'visalia-ca', 'CA'),
  ('Simi Valley', 'simi-valley-ca', 'CA'),
  ('Concord', 'concord-ca', 'CA'),
  ('Roseville', 'roseville-ca', 'CA'),
  ('Victorville', 'victorville-ca', 'CA'),
  ('Berkeley', 'berkeley-ca', 'CA'),
  ('El Cajon', 'el-cajon-ca', 'CA'),
  ('Vallejo', 'vallejo-ca', 'CA'),
  ('Carlsbad', 'carlsbad-ca', 'CA'),
  ('Clovis', 'clovis-ca', 'CA'),
  ('Downey', 'downey-ca', 'CA'),
  ('Costa Mesa', 'costa-mesa-ca', 'CA'),
  ('San Mateo', 'san-mateo-ca', 'CA'),
  ('Ventura', 'ventura-ca', 'CA'),
  ('West Covina', 'west-covina-ca', 'CA'),
  ('Fairfield', 'fairfield-ca', 'CA'),
  ('Murrieta', 'murrieta-ca', 'CA'),
  ('Norwalk', 'norwalk-ca', 'CA'),
  ('Burbank', 'burbank-ca', 'CA'),
  ('Daly City', 'daly-city-ca', 'CA'),
  ('Richmond', 'richmond-ca', 'CA'),
  ('Antioch', 'antioch-ca', 'CA'),
  ('Boulder', 'boulder-co', 'CO'),
  -- Colorado
  ('Denver', 'denver-co', 'CO'),
  ('Colorado Springs', 'colorado-springs-co', 'CO'),
  ('Aurora', 'aurora-co', 'CO'),
  ('Fort Collins', 'fort-collins-co', 'CO'),
  ('Lakewood', 'lakewood-co', 'CO'),
  ('Thornton', 'thornton-co', 'CO'),
  ('Arvada', 'arvada-co', 'CO'),
  ('Westminster', 'westminster-co', 'CO'),
  ('Pueblo', 'pueblo-co', 'CO'),
  ('Centennial', 'centennial-co', 'CO'),
  ('Longmont', 'longmont-co', 'CO'),
  ('Loveland', 'loveland-co', 'CO'),
  ('Grand Junction', 'grand-junction-co', 'CO'),
  ('Greeley', 'greeley-co', 'CO'),
  ('Boulder', 'boulder-co-2', 'CO'),
  -- Connecticut
  ('Bridgeport', 'bridgeport-ct', 'CT'),
  ('New Haven', 'new-haven-ct', 'CT'),
  ('Stamford', 'stamford-ct', 'CT'),
  ('Hartford', 'hartford-ct', 'CT'),
  ('Waterbury', 'waterbury-ct', 'CT'),
  ('Norwalk', 'norwalk-ct', 'CT'),
  ('Danbury', 'danbury-ct', 'CT'),
  ('New Britain', 'new-britain-ct', 'CT'),
  ('Bristol', 'bristol-ct', 'CT'),
  ('Meriden', 'meriden-ct', 'CT'),
  ('West Haven', 'west-haven-ct', 'CT'),
  ('Milford', 'milford-ct', 'CT'),
  ('Greenwich', 'greenwich-ct', 'CT'),
  ('Shelton', 'shelton-ct', 'CT'),
  -- Delaware
  ('Wilmington', 'wilmington-de', 'DE'),
  ('Dover', 'dover-de', 'DE'),
  ('Newark', 'newark-de', 'DE'),
  ('Middletown', 'middletown-de', 'DE'),
  ('Smyrna', 'smyrna-de', 'DE'),
  ('Milford', 'milford-de', 'DE'),
  ('Seaford', 'seaford-de', 'DE'),
  ('Georgetown', 'georgetown-de', 'DE'),
  ('Elsmere', 'elsmere-de', 'DE'),
  ('New Castle', 'new-castle-de', 'DE'),
  -- Florida
  ('Miami', 'miami', 'FL'),
  ('Jacksonville', 'jacksonville-fl', 'FL'),
  ('Tampa', 'tampa-fl', 'FL'),
  ('Orlando', 'orlando-fl', 'FL'),
  ('St. Petersburg', 'st-petersburg-fl', 'FL'),
  ('Hialeah', 'hialeah-fl', 'FL'),
  ('Tallahassee', 'tallahassee-fl', 'FL'),
  ('Fort Lauderdale', 'fort-lauderdale-fl', 'FL'),
  ('Port St. Lucie', 'port-st-lucie-fl', 'FL'),
  ('Cape Coral', 'cape-coral-fl', 'FL'),
  ('Pembroke Pines', 'pembroke-pines-fl', 'FL'),
  ('Hollywood', 'hollywood-fl', 'FL'),
  ('Gainesville', 'gainesville-fl', 'FL'),
  ('Miramar', 'miramar-fl', 'FL'),
  ('Coral Springs', 'coral-springs-fl', 'FL'),
  ('Clearwater', 'clearwater-fl', 'FL'),
  ('Palm Bay', 'palm-bay-fl', 'FL'),
  ('Lakeland', 'lakeland-fl', 'FL'),
  ('Pompano Beach', 'pompano-beach-fl', 'FL'),
  ('West Palm Beach', 'west-palm-beach-fl', 'FL'),
  ('Davie', 'davie-fl', 'FL'),
  ('Miami Gardens', 'miami-gardens-fl', 'FL'),
  ('Sunrise', 'sunrise-fl', 'FL'),
  ('Plantation', 'plantation-fl', 'FL'),
  ('Boca Raton', 'boca-raton-fl', 'FL'),
  ('Tallahassee', 'tallahassee-fl-2', 'FL'),
  ('Deltona', 'deltona-fl', 'FL'),
  ('St. Cloud', 'st-cloud-fl', 'FL'),
  ('Fort Myers', 'fort-myers-fl', 'FL'),
  ('Kissimmee', 'kissimmee-fl', 'FL'),
  ('Homestead', 'homestead-fl', 'FL'),
  ('Tamarac', 'tamarac-fl', 'FL'),
  ('Delray Beach', 'delray-beach-fl', 'FL'),
  ('Daytona Beach', 'daytona-beach-fl', 'FL'),
  ('Naples', 'naples-fl', 'FL'),
  ('St. Augustine', 'st-augustine-fl', 'FL'),
  ('Sarasota', 'sarasota-fl', 'FL'),
  ('Pensacola', 'pensacola-fl', 'FL'),
  ('Doral', 'doral-fl', 'FL'),
  ('Sunrise', 'sunrise-fl-2', 'FL'),
  -- Georgia
  ('Atlanta', 'atlanta', 'GA'),
  ('Savannah', 'savannah-ga', 'GA'),
  ('Augusta', 'augusta-ga', 'GA'),
  ('Columbus', 'columbus-ga', 'GA'),
  ('Macon', 'macon-ga', 'GA'),
  ('Athens', 'athens-ga', 'GA'),
  ('Sandy Springs', 'sandy-springs-ga', 'GA'),
  ('Roswell', 'roswell-ga', 'GA'),
  ('Johns Creek', 'johns-creek-ga', 'GA'),
  ('Albany', 'albany-ga', 'GA'),
  ('Warner Robins', 'warner-robins-ga', 'GA'),
  ('Alpharetta', 'alpharetta-ga', 'GA'),
  ('Marietta', 'marietta-ga', 'GA'),
  ('Smyrna', 'smyrna-ga', 'GA'),
  ('Valdosta', 'valdosta-ga', 'GA'),
  ('Kennesaw', 'kennesaw-ga', 'GA'),
  ('Statesboro', 'statesboro-ga', 'GA'),
  ('Hinesville', 'hinesville-ga', 'GA'),
  ('Dublin', 'dublin-ga', 'GA'),
  ('Milledgeville', 'milledgeville-ga', 'GA'),
  ('Cartersville', 'cartersville-ga', 'GA'),
  ('Lawrenceville', 'lawrenceville-ga', 'GA'),
  ('Peachtree City', 'peachtree-city-ga', 'GA'),
  ('Dalton', 'dalton-ga', 'GA'),
  ('Gainesville', 'gainesville-ga', 'GA'),
  ('Newnan', 'newnan-ga', 'GA'),
  ('Carrollton', 'carrollton-ga', 'GA'),
  ('Rome', 'rome-ga', 'GA'),
  ('LaGrange', 'lagrange-ga', 'GA'),
  ('Brunswick', 'brunswick-ga', 'GA'),
  ('Vidalia', 'vidalia-ga', 'GA'),
  ('Tifton', 'tifton-ga', 'GA'),
  ('Waycross', 'waycross-ga', 'GA'),
  ('Thomasville', 'thomasville-ga', 'GA'),
  ('Moultrie', 'moultrie-ga', 'GA'),
  ('Fitzgerald', 'fitzgerald-ga', 'GA'),
  ('Canton', 'canton-ga', 'GA'),
  ('Woodstock', 'woodstock-ga', 'GA'),
  ('Acworth', 'acworth-ga', 'GA'),
  ('Powder Springs', 'powder-springs-ga', 'GA'),
  ('Douglasville', 'douglasville-ga', 'GA'),
  ('Snellville', 'snellville-ga', 'GA'),
  ('Lilburn', 'lilburn-ga', 'GA'),
  ('Norcross', 'norcross-ga', 'GA'),
  ('Duluth', 'duluth-ga', 'GA'),
  ('Suwanee', 'suwanee-ga', 'GA'),
  ('Sugar Hill', 'sugar-hill-ga', 'GA'),
  ('Buford', 'buford-ga', 'GA'),
  ('Cumming', 'cumming-ga', 'GA'),
  ('Conyers', 'conyers-ga', 'GA'),
  ('Covington', 'covington-ga', 'GA'),
  ('Griffin', 'griffin-ga', 'GA'),
  ('Forsyth', 'forsyth-ga', 'GA'),
  ('Morrow', 'morrow-ga', 'GA'),
  ('Forest Park', 'forest-park-ga', 'GA'),
  ('College Park', 'college-park-ga', 'GA'),
  ('East Point', 'east-point-ga', 'GA'),
  ('Union City', 'union-city-ga', 'GA'),
  ('Fairburn', 'fairburn-ga', 'GA'),
  ('Hiram', 'hiram-ga', 'GA'),
  ('Villa Rica', 'villa-rica-ga', 'GA'),
  ('Dallas', 'dallas-ga', 'GA'),
  ('Dallas', 'dallas-ga-2', 'GA'),
  -- Hawaii
  ('Honolulu', 'honolulu-hi', 'HI'),
  ('Hilo', 'hilo-hi', 'HI'),
  ('Kailua', 'kailua-hi', 'HI'),
  ('Kapolei', 'kapolei-hi', 'HI'),
  ('Kaneohe', 'kaneohe-hi', 'HI'),
  ('Waipahu', 'waipahu-hi', 'HI'),
  ('Pearl City', 'pearl-city-hi', 'HI'),
  ('Mililani Town', 'mililani-town-hi', 'HI'),
  ('Kihei', 'kihei-hi', 'HI'),
  ('Wailuku', 'wailuku-hi', 'HI'),
  -- Idaho
  ('Boise', 'boise-id', 'ID'),
  ('Meridian', 'meridian-id', 'ID'),
  ('Nampa', 'nampa-id', 'ID'),
  ('Idaho Falls', 'idaho-falls-id', 'ID'),
  ('Pocatello', 'pocatello-id', 'ID'),
  ('Caldwell', 'caldwell-id', 'ID'),
  ('Coeur d''Alene', 'coeur-dalene-id', 'ID'),
  ('Twin Falls', 'twin-falls-id', 'ID'),
  ('Lewiston', 'lewiston-id', 'ID'),
  ('Post Falls', 'post-falls-id', 'ID'),
  ('Rexburg', 'rexburg-id', 'ID'),
  ('Moscow', 'moscow-id', 'ID'),
  ('Eagle', 'eagle-id', 'ID'),
  -- Illinois
  ('Chicago', 'chicago', 'IL'),
  ('Aurora', 'aurora-il', 'IL'),
  ('Naperville', 'naperville-il', 'IL'),
  ('Joliet', 'joliet-il', 'IL'),
  ('Rockford', 'rockford-il', 'IL'),
  ('Springfield', 'springfield-il', 'IL'),
  ('Elgin', 'elgin-il', 'IL'),
  ('Peoria', 'peoria-il', 'IL'),
  ('Champaign', 'champaign-il', 'IL'),
  ('Waukegan', 'waukegan-il', 'IL'),
  ('Cicero', 'cicero-il', 'IL'),
  ('Bloomington', 'bloomington-il', 'IL'),
  ('Evanston', 'evanston-il', 'IL'),
  ('Decatur', 'decatur-il', 'IL'),
  ('Schaumburg', 'schaumburg-il', 'IL'),
  ('Buffalo Grove', 'buffalo-grove-il', 'IL'),
  ('Bolingbrook', 'bolingbrook-il', 'IL'),
  ('Carol Stream', 'carol-stream-il', 'IL'),
  ('Moline', 'moline-il', 'IL'),
  ('Normal', 'normal-il', 'IL'),
  ('Oak Lawn', 'oak-lawn-il', 'IL'),
  ('Tinley Park', 'tinley-park-il', 'IL'),
  ('Skokie', 'skokie-il', 'IL'),
  ('Des Plaines', 'des-plaines-il', 'IL'),
  ('Orland Park', 'orland-park-il', 'IL'),
  ('Palatine', 'palatine-il', 'IL'),
  ('Oak Park', 'oak-park-il', 'IL'),
  ('Wheaton', 'wheaton-il', 'IL'),
  ('Glenview', 'glenview-il', 'IL'),
  ('Downers Grove', 'downers-grove-il', 'IL'),
  ('Mount Prospect', 'mount-prospect-il', 'IL'),
  ('Plainfield', 'plainfield-il', 'IL'),
  ('Romeoville', 'romeoville-il', 'IL'),
  ('Hoffman Estates', 'hoffman-estates-il', 'IL'),
  ('DeKalb', 'dekalb-il', 'IL'),
  ('Quincy', 'quincy-il', 'IL'),
  ('Champaign', 'champaign-il-2', 'IL'),
  -- Indiana
  ('Indianapolis', 'indianapolis-in', 'IN'),
  ('Fort Wayne', 'fort-wayne-in', 'IN'),
  ('Evansville', 'evansville-in', 'IN'),
  ('South Bend', 'south-bend-in', 'IN'),
  ('Carmel', 'carmel-in', 'IN'),
  ('Fishers', 'fishers-in', 'IN'),
  ('Bloomington', 'bloomington-in', 'IN'),
  ('Hammond', 'hammond-in', 'IN'),
  ('Gary', 'gary-in', 'IN'),
  ('Lafayette', 'lafayette-in', 'IN'),
  ('Muncie', 'muncie-in', 'IN'),
  ('Noblesville', 'noblesville-in', 'IN'),
  ('Greenwood', 'greenwood-in', 'IN'),
  ('Anderson', 'anderson-in', 'IN'),
  ('Terre Haute', 'terre-haute-in', 'IN'),
  ('Elkhart', 'elkhart-in', 'IN'),
  ('Mishawaka', 'mishawaka-in', 'IN'),
  ('Columbus', 'columbus-in', 'IN'),
  ('Jeffersonville', 'jeffersonville-in', 'IN'),
  ('Portage', 'portage-in', 'IN'),
  ('Valparaiso', 'valparaiso-in', 'IN'),
  ('Goshen', 'goshen-in', 'IN'),
  ('Plainfield', 'plainfield-in', 'IN'),
  ('Franklin', 'franklin-in', 'IN'),
  ('Michigan City', 'michigan-city-in', 'IN'),
  ('La Porte', 'la-porte-in', 'IN'),
  ('New Albany', 'new-albany-in', 'IN'),
  ('Richmond', 'richmond-in', 'IN'),
  ('Seymour', 'seymour-in', 'IN'),
  ('Huntington', 'huntington-in', 'IN'),
  -- Iowa
  ('Des Moines', 'des-moines-ia', 'IA'),
  ('Cedar Rapids', 'cedar-rapids-ia', 'IA'),
  ('Davenport', 'davenport-ia', 'IA'),
  ('Sioux City', 'sioux-city-ia', 'IA'),
  ('Iowa City', 'iowa-city-ia', 'IA'),
  ('Waterloo', 'waterloo-ia', 'IA'),
  ('Ames', 'ames-ia', 'IA'),
  ('West Des Moines', 'west-des-moines-ia', 'IA'),
  ('Council Bluffs', 'council-bluffs-ia', 'IA'),
  ('Dubuque', 'dubuque-ia', 'IA'),
  ('Ankeny', 'ankeney-ia', 'IA'),
  ('Urbandale', 'urbandale-ia', 'IA'),
  ('Cedar Falls', 'cedar-falls-ia', 'IA'),
  ('Marion', 'marion-ia', 'IA'),
  ('Bettendorf', 'bettendorf-ia', 'IA'),
  ('Mason City', 'mason-city-ia', 'IA'),
  ('Marshalltown', 'marshalltown-ia', 'IA'),
  ('Clinton', 'clinton-ia', 'IA'),
  ('Ottumwa', 'ottumwa-ia', 'IA'),
  ('Fort Dodge', 'fort-dodge-ia', 'IA'),
  -- Kansas
  ('Wichita', 'wichita-ks', 'KS'),
  ('Overland Park', 'overland-park-ks', 'KS'),
  ('Kansas City', 'kansas-city-ks', 'KS'),
  ('Olathe', 'olathe-ks', 'KS'),
  ('Topeka', 'topeka-ks', 'KS'),
  ('Lawrence', 'lawrence-ks', 'KS'),
  ('Shawnee', 'shawnee-ks', 'KS'),
  ('Manhattan', 'manhattan-ks', 'KS'),
  ('Lenexa', 'lenexa-ks', 'KS'),
  ('Leavenworth', 'leavenworth-ks', 'KS'),
  ('Leawood', 'leawood-ks', 'KS'),
  ('Hutchinson', 'hutchinson-ks', 'KS'),
  ('Dodge City', 'dodge-city-ks', 'KS'),
  ('Emporia', 'emporia-ks', 'KS'),
  ('Garden City', 'garden-city-ks', 'KS'),
  ('Junction City', 'junction-city-ks', 'KS'),
  ('Pittsburg', 'pittsburg-ks', 'KS'),
  ('Newton', 'newton-ks', 'KS'),
  -- Kentucky
  ('Louisville', 'louisville-ky', 'KY'),
  ('Lexington', 'lexington-ky', 'KY'),
  ('Bowling Green', 'bowling-green-ky', 'KY'),
  ('Owensboro', 'owensboro-ky', 'KY'),
  ('Covington', 'covington-ky', 'KY'),
  ('Hopkinsville', 'hopkinsville-ky', 'KY'),
  ('Richmond', 'richmond-ky', 'KY'),
  ('Florence', 'florence-ky', 'KY'),
  ('Georgetown', 'georgetown-ky', 'KY'),
  ('Henderson', 'henderson-ky', 'KY'),
  ('Frankfort', 'frankfort-ky', 'KY'),
  ('Paducah', 'paducah-ky', 'KY'),
  ('Ashland', 'ashland-ky', 'KY'),
  ('Nicholasville', 'nicholasville-ky', 'KY'),
  ('Elizabethtown', 'elizabethtown-ky', 'KY'),
  ('Somerset', 'somerset-ky', 'KY'),
  ('Madisonville', 'madisonville-ky', 'KY'),
  ('Danville', 'danville-ky', 'KY'),
  ('Morehead', 'morehead-ky', 'KY'),
  ('Murray', 'murray-ky', 'KY'),
  -- Louisiana
  ('New Orleans', 'new-orleans-la', 'LA'),
  ('Baton Rouge', 'baton-rouge-la', 'LA'),
  ('Shreveport', 'shreveport-la', 'LA'),
  ('Lafayette', 'lafayette-la', 'LA'),
  ('Lake Charles', 'lake-charles-la', 'LA'),
  ('Kenner', 'kenner-la', 'LA'),
  ('Bossier City', 'bossier-city-la', 'LA'),
  ('Monroe', 'monroe-la', 'LA'),
  ('Alexandria', 'alexandria-la', 'LA'),
  ('Houma', 'houma-la', 'LA'),
  ('New Iberia', 'new-iberia-la', 'LA'),
  ('Slidell', 'slidell-la', 'LA'),
  ('Central', 'central-la', 'LA'),
  ('Marrero', 'marrero-la', 'LA'),
  ('Ruston', 'ruston-la', 'LA'),
  ('Hammond', 'hammond-la', 'LA'),
  ('Natchitoches', 'natchitoches-la', 'LA'),
  ('Opelousas', 'opelousas-la', 'LA'),
  ('Morgan City', 'morgan-city-la', 'LA'),
  ('Thibodaux', 'thibodaux-la', 'LA'),
  -- Maine
  ('Portland', 'portland-me', 'ME'),
  ('Lewiston', 'lewiston-me', 'ME'),
  ('Bangor', 'bangor-me', 'ME'),
  ('South Portland', 'south-portland-me', 'ME'),
  ('Auburn', 'auburn-me', 'ME'),
  ('Biddeford', 'biddeford-me', 'ME'),
  ('Sanford', 'sanford-me', 'ME'),
  ('Augusta', 'augusta-me', 'ME'),
  ('Saco', 'saco-me', 'ME'),
  ('Westbrook', 'westbrook-me', 'ME'),
  ('Waterville', 'waterville-me', 'ME'),
  ('Presque Isle', 'presque-isle-me', 'ME'),
  ('Scarborough', 'scarborough-me', 'ME'),
  ('Gorham', 'gorham-me', 'ME'),
  ('Orono', 'orono-me', 'ME'),
  -- Maryland
  ('Baltimore', 'baltimore-md', 'MD'),
  ('Frederick', 'frederick-md', 'MD'),
  ('Rockville', 'rockville-md', 'MD'),
  ('Gaithersburg', 'gaithersburg-md', 'MD'),
  ('Bowie', 'bowie-md', 'MD'),
  ('Hagerstown', 'hagerstown-md', 'MD'),
  ('Annapolis', 'annapolis-md', 'MD'),
  ('Salisbury', 'salisbury-md', 'MD'),
  ('College Park', 'college-park-md', 'MD'),
  ('Greenbelt', 'greenbelt-md', 'MD'),
  ('Laurel', 'laurel-md', 'MD'),
  ('Silver Spring', 'silver-spring-md', 'MD'),
  ('Takoma Park', 'takoma-park-md', 'MD'),
  ('Bethesda', 'bethesda-md', 'MD'),
  ('Ellicott City', 'ellicott-city-md', 'MD'),
  ('Columbia', 'columbia-md', 'MD'),
  ('Towson', 'towson-md', 'MD'),
  ('Catonsville', 'catonsville-md', 'MD'),
  ('Dundalk', 'dundalk-md', 'MD'),
  ('Glen Burnie', 'glen-burnie-md', 'MD'),
  -- Massachusetts
  ('Boston', 'boston-ma', 'MA'),
  ('Worcester', 'worcester-ma', 'MA'),
  ('Springfield', 'springfield-ma', 'MA'),
  ('Cambridge', 'cambridge-ma', 'MA'),
  ('Lowell', 'lowell-ma', 'MA'),
  ('Brockton', 'brockton-ma', 'MA'),
  ('New Bedford', 'new-bedford-ma', 'MA'),
  ('Quincy', 'quincy-ma', 'MA'),
  ('Lynn', 'lynn-ma', 'MA'),
  ('Fall River', 'fall-river-ma', 'MA'),
  ('Newton', 'newton-ma', 'MA'),
  ('Lawrence', 'lawrence-ma', 'MA'),
  ('Somerville', 'somerville-ma', 'MA'),
  ('Framingham', 'framingham-ma', 'MA'),
  ('Haverhill', 'haverhill-ma', 'MA'),
  ('Weymouth', 'weymouth-ma', 'MA'),
  ('Malden', 'malden-ma', 'MA'),
  ('Brookline', 'brookline-ma', 'MA'),
  ('Plymouth', 'plymouth-ma', 'MA'),
  ('Medford', 'medford-ma', 'MA'),
  ('Taunton', 'taunton-ma', 'MA'),
  ('Chicopee', 'chicopee-ma', 'MA'),
  ('Waltham', 'waltham-ma', 'MA'),
  ('Revere', 'revere-ma', 'MA'),
  ('Peabody', 'peabody-ma', 'MA'),
  -- Michigan
  ('Detroit', 'detroit-mi', 'MI'),
  ('Grand Rapids', 'grand-rapids-mi', 'MI'),
  ('Warren', 'warren-mi', 'MI'),
  ('Sterling Heights', 'sterling-heights-mi', 'MI'),
  ('Ann Arbor', 'ann-arbor-mi', 'MI'),
  ('Lansing', 'lansing-mi', 'MI'),
  ('Flint', 'flint-mi', 'MI'),
  ('Dearborn', 'dearborn-mi', 'MI'),
  ('Livonia', 'livonia-mi', 'MI'),
  ('Troy', 'troy-mi', 'MI'),
  ('Westland', 'westland-mi', 'MI'),
  ('Farmington Hills', 'farmington-hills-mi', 'MI'),
  ('Kalamazoo', 'kalamazoo-mi', 'MI'),
  ('Wyoming', 'wyoming-mi', 'MI'),
  ('Southfield', 'southfield-mi', 'MI'),
  ('Rochester Hills', 'rochester-hills-mi', 'MI'),
  ('Taylor', 'taylor-mi', 'MI'),
  ('Pontiac', 'pontiac-mi', 'MI'),
  ('St. Clair Shores', 'st-clair-shores-mi', 'MI'),
  ('Saginaw', 'saginaw-mi', 'MI'),
  ('Battle Creek', 'battle-creek-mi', 'MI'),
  ('Portage', 'portage-mi', 'MI'),
  ('Midland', 'midland-mi', 'MI'),
  ('Muskegon', 'muskegon-mi', 'MI'),
  ('Monroe', 'monroe-mi', 'MI'),
  ('Dearborn Heights', 'dearborn-heights-mi', 'MI'),
  ('Ypsilanti', 'ypsilanti-mi', 'MI'),
  ('Novi', 'novi-mi', 'MI'),
  ('Shelby Township', 'shelby-township-mi', 'MI'),
  ('Macomb', 'macomb-mi', 'MI'),
  -- Minnesota
  ('Minneapolis', 'minneapolis-mn', 'MN'),
  ('Saint Paul', 'saint-paul-mn', 'MN'),
  ('Rochester', 'rochester-mn', 'MN'),
  ('Duluth', 'duluth-mn', 'MN'),
  ('Bloomington', 'bloomington-mn', 'MN'),
  ('Brooklyn Park', 'brooklyn-park-mn', 'MN'),
  ('Plymouth', 'plymouth-mn', 'MN'),
  ('Maple Grove', 'maple-grove-mn', 'MN'),
  ('Woodbury', 'woodbury-mn', 'MN'),
  ('St. Cloud', 'st-cloud-mn', 'MN'),
  ('Eagan', 'eagan-mn', 'MN'),
  ('Coon Rapids', 'coon-rapids-mn', 'MN'),
  ('Eden Prairie', 'eden-prairie-mn', 'MN'),
  ('Minnetonka', 'minnetonka-mn', 'MN'),
  ('Burnsville', 'burnsville-mn', 'MN'),
  ('Apple Valley', 'apple-valley-mn', 'MN'),
  ('Blaine', 'blaine-mn', 'MN'),
  ('Lakeville', 'lakeville-mn', 'MN'),
  ('Mankato', 'mankato-mn', 'MN'),
  ('Moorhead', 'moorhead-mn', 'MN'),
  -- Mississippi
  ('Jackson', 'jackson-ms', 'MS'),
  ('Gulfport', 'gulfport-ms', 'MS'),
  ('Southaven', 'southaven-ms', 'MS'),
  ('Hattiesburg', 'hattiesburg-ms', 'MS'),
  ('Biloxi', 'biloxi-ms', 'MS'),
  ('Meridian', 'meridian-ms', 'MS'),
  ('Tupelo', 'tupelo-ms', 'MS'),
  ('Greenville', 'greenville-ms', 'MS'),
  ('Olive Branch', 'olive-branch-ms', 'MS'),
  ('Horn Lake', 'horn-lake-ms', 'MS'),
  ('Clinton', 'clinton-ms', 'MS'),
  ('Pearl', 'pearl-ms', 'MS'),
  ('Starkville', 'starkville-ms', 'MS'),
  ('Oxford', 'oxford-ms', 'MS'),
  ('Columbus', 'columbus-ms', 'MS'),
  ('Vicksburg', 'vicksburg-ms', 'MS'),
  ('Pascagoula', 'pascagoula-ms', 'MS'),
  ('Laurel', 'laurel-ms', 'MS'),
  ('Brandon', 'brandon-ms', 'MS'),
  ('Madison', 'madison-ms', 'MS'),
  -- Missouri
  ('Kansas City', 'kansas-city-mo', 'MO'),
  ('Saint Louis', 'saint-louis-mo', 'MO'),
  ('Springfield', 'springfield-mo', 'MO'),
  ('Independence', 'independence-mo', 'MO'),
  ('Columbia', 'columbia-mo', 'MO'),
  ('Lee''s Summit', 'lees-summit-mo', 'MO'),
  ('O''Fallon', 'ofallon-mo', 'MO'),
  ('St. Joseph', 'st-joseph-mo', 'MO'),
  ('St. Charles', 'st-charles-mo', 'MO'),
  ('St. Peters', 'st-peters-mo', 'MO'),
  ('Blue Springs', 'blue-springs-mo', 'MO'),
  ('Florissant', 'florissant-mo', 'MO'),
  ('Joplin', 'joplin-mo', 'MO'),
  ('Chesterfield', 'chesterfield-mo', 'MO'),
  ('Jefferson City', 'jefferson-city-mo', 'MO'),
  ('Cape Girardeau', 'cape-girardeau-mo', 'MO'),
  ('Wentzville', 'wentzville-mo', 'MO'),
  ('Sedalia', 'sedalia-mo', 'MO'),
  ('University City', 'university-city-mo', 'MO'),
  ('Hannibal', 'hannibal-mo', 'MO'),
  -- Montana
  ('Billings', 'billings-mt', 'MT'),
  ('Missoula', 'missoula-mt', 'MT'),
  ('Great Falls', 'great-falls-mt', 'MT'),
  ('Bozeman', 'bozeman-mt', 'MT'),
  ('Butte', 'butte-mt', 'MT'),
  ('Helena', 'helena-mt', 'MT'),
  ('Kalispell', 'kalispell-mt', 'MT'),
  ('Havre', 'havre-mt', 'MT'),
  ('Anaconda', 'anaconda-mt', 'MT'),
  ('Miles City', 'miles-city-mt', 'MT'),
  ('Livingston', 'livingston-mt', 'MT'),
  ('Laurel', 'laurel-mt', 'MT'),
  ('Whitefish', 'whitefish-mt', 'MT'),
  ('Dillon', 'dillon-mt', 'MT'),
  -- Nebraska
  ('Omaha', 'omaha-ne', 'NE'),
  ('Lincoln', 'lincoln-ne', 'NE'),
  ('Bellevue', 'bellevue-ne', 'NE'),
  ('Grand Island', 'grand-island-ne', 'NE'),
  ('Kearney', 'kearney-ne', 'NE'),
  ('Fremont', 'freemont-ne', 'NE'),
  ('Hastings', 'hastings-ne', 'NE'),
  ('Norfolk', 'norfolk-ne', 'NE'),
  ('North Platte', 'north-platte-ne', 'NE'),
  ('Columbus', 'columbus-ne', 'NE'),
  ('Scottsbluff', 'scottsbluff-ne', 'NE'),
  ('La Vista', 'la-vista-ne', 'NE'),
  ('Papillion', 'papillion-ne', 'NE'),
  ('Chadron', 'chadron-ne', 'NE'),
  ('Alliance', 'alliance-ne', 'NE'),
  ('Beatrice', 'beatrice-ne', 'NE'),
  ('York', 'york-ne', 'NE'),
  -- Nevada
  ('Las Vegas', 'las-vegas-nv', 'NV'),
  ('Henderson', 'henderson-nv', 'NV'),
  ('Reno', 'reno-nv', 'NV'),
  ('North Las Vegas', 'north-las-vegas-nv', 'NV'),
  ('Sparks', 'sparks-nv', 'NV'),
  ('Carson City', 'carson-city-nv', 'NV'),
  ('Fernley', 'fernley-nv', 'NV'),
  ('Elko', 'elko-nv', 'NV'),
  ('Mesquite', 'mesquite-nv', 'NV'),
  ('Boulder City', 'boulder-city-nv', 'NV'),
  ('Fallon', 'fallon-nv', 'NV'),
  ('Winnemucca', 'winnemucca-nv', 'NV'),
  ('West Wendover', 'west-wendover-nv', 'NV'),
  ('Ely', 'ely-nv', 'NV'),
  -- New Hampshire
  ('Manchester', 'manchester-nh', 'NH'),
  ('Nashua', 'nashua-nh', 'NH'),
  ('Concord', 'concord-nh', 'NH'),
  ('Derry', 'derry-nh', 'NH'),
  ('Rochester', 'rochester-nh', 'NH'),
  ('Salem', 'salem-nh', 'NH'),
  ('Dover', 'dover-nh', 'NH'),
  ('Merrimack', 'merrimack-nh', 'NH'),
  ('Londonderry', 'londonderry-nh', 'NH'),
  ('Hudson', 'hudson-nh', 'NH'),
  ('Keene', 'keene-nh', 'NH'),
  ('Portsmouth', 'portsmouth-nh', 'NH'),
  ('Laconia', 'laconia-nh', 'NH'),
  ('Lebanon', 'lebanon-nh', 'NH'),
  -- New Jersey
  ('Newark', 'newark-nj', 'NJ'),
  ('Jersey City', 'jersey-city-nj', 'NJ'),
  ('Paterson', 'paterson-nj', 'NJ'),
  ('Elizabeth', 'elizabeth-nj', 'NJ'),
  ('Edison', 'edison-nj', 'NJ'),
  ('Woodbridge', 'woodbridge-nj', 'NJ'),
  ('Lakewood', 'lakewood-nj', 'NJ'),
  ('Toms River', 'toms-river-nj', 'NJ'),
  ('Hamilton', 'hamilton-nj', 'NJ'),
  ('Trenton', 'trenton-nj', 'NJ'),
  ('Clifton', 'clifton-nj', 'NJ'),
  ('Camden', 'camden-nj', 'NJ'),
  ('Brick', 'brick-nj', 'NJ'),
  ('Cherry Hill', 'cherry-hill-nj', 'NJ'),
  ('Passaic', 'passaic-nj', 'NJ'),
  ('Union City', 'union-city-nj', 'NJ'),
  ('Bayonne', 'bayonne-nj', 'NJ')
  -- New Jersey continued
  ,('East Orange', 'east-orange-nj', 'NJ'),
  ('Franklin', 'franklin-nj', 'NJ'),
  ('Vineland', 'vineland-nj', 'NJ'),
  ('New Brunswick', 'new-brunswick-nj', 'NJ'),
  ('Atlantic City', 'atlantic-city-nj', 'NJ'),
  ('Princeton', 'princeton-nj', 'NJ'),
  ('Hoboken', 'hoboken-nj', 'NJ'),
  ('Morristown', 'morristown-nj', 'NJ'),
  ('Mount Laurel', 'mount-laurel-nj', 'NJ'),
  ('Paramus', 'paramus-nj', 'NJ'),
  ('Bridgewater', 'bridgewater-nj', 'NJ'),
  ('South Brunswick', 'south-brunswick-nj', 'NJ'),
  ('Egg Harbor', 'egg-harbor-nj', 'NJ'),
  -- New Mexico
  ('Albuquerque', 'albuquerque-nm', 'NM'),
  ('Las Cruces', 'las-cruces-nm', 'NM'),
  ('Rio Rancho', 'rio-rancho-nm', 'NM'),
  ('Santa Fe', 'santa-fe-nm', 'NM'),
  ('Roswell', 'roswell-nm', 'NM'),
  ('Farmington', 'farmington-nm', 'NM'),
  ('Clovis', 'clovis-nm', 'NM'),
  ('Hobbs', 'hobbs-nm', 'NM'),
  ('Alamogordo', 'alamogordo-nm', 'NM'),
  ('Carlsbad', 'carlsbad-nm', 'NM'),
  ('Gallup', 'gallup-nm', 'NM'),
  ('Deming', 'deming-nm', 'NM'),
  ('Los Alamos', 'los-alamos-nm', 'NM'),
  ('Silver City', 'silver-city-nm', 'NM'),
  -- New York
  ('New York', 'new-york', 'NY'),
  ('Buffalo', 'buffalo-ny', 'NY'),
  ('Rochester', 'rochester-ny', 'NY'),
  ('Yonkers', 'yonkers-ny', 'NY'),
  ('Syracuse', 'syracuse-ny', 'NY'),
  ('Albany', 'albany-ny', 'NY'),
  ('New Rochelle', 'new-rochelle-ny', 'NY'),
  ('Mount Vernon', 'mount-vernon-ny', 'NY'),
  ('Schenectady', 'schenectady-ny', 'NY'),
  ('Utica', 'utica-ny', 'NY'),
  ('White Plains', 'white-plains-ny', 'NY'),
  ('Hempstead', 'hempstead-ny', 'NY'),
  ('Troy', 'troy-ny', 'NY'),
  ('Niagara Falls', 'niagara-falls-ny', 'NY'),
  ('Binghamton', 'binghamton-ny', 'NY'),
  ('Freeport', 'freeport-ny', 'NY'),
  ('Valley Stream', 'valley-stream-ny', 'NY'),
  ('Long Beach', 'long-beach-ny', 'NY'),
  ('Ithaca', 'ithaca-ny', 'NY'),
  ('Rome', 'rome-ny', 'NY'),
  ('Poughkeepsie', 'poughkeepsie-ny', 'NY'),
  ('North Tonawanda', 'north-tonawanda-ny', 'NY'),
  ('Jamestown', 'jamestown-ny', 'NY'),
  ('Elmira', 'elmira-ny', 'NY'),
  ('Saratoga Springs', 'saratoga-springs-ny', 'NY'),
  ('Plattsburgh', 'plattsburgh-ny', 'NY'),
  ('Auburn', 'auburn-ny', 'NY'),
  ('Glens Falls', 'glens-falls-ny', 'NY'),
  ('Kingston', 'kingston-ny', 'NY'),
  ('Oswego', 'oswego-ny', 'NY'),
  -- North Carolina
  ('Charlotte', 'charlotte-nc', 'NC'),
  ('Raleigh', 'raleigh-nc', 'NC'),
  ('Greensboro', 'greensboro-nc', 'NC'),
  ('Durham', 'durham-nc', 'NC'),
  ('Winston-Salem', 'winston-salem-nc', 'NC'),
  ('Fayetteville', 'fayetteville-nc', 'NC'),
  ('Cary', 'cary-nc', 'NC'),
  ('Wilmington', 'wilmington-nc', 'NC'),
  ('High Point', 'high-point-nc', 'NC'),
  ('Greenville', 'greenville-nc', 'NC'),
  ('Asheville', 'asheville-nc', 'NC'),
  ('Concord', 'concord-nc', 'NC'),
  ('Gastonia', 'gastonia-nc', 'NC'),
  ('Jacksonville', 'jacksonville-nc', 'NC'),
  ('Chapel Hill', 'chapel-hill-nc', 'NC'),
  ('Rocky Mount', 'rocky-mount-nc', 'NC'),
  ('Burlington', 'burlington-nc', 'NC'),
  ('Huntersville', 'huntersville-nc', 'NC'),
  ('Wilson', 'wilson-nc', 'NC'),
  ('Kannapolis', 'kannapolis-nc', 'NC'),
  ('Apex', 'apex-nc', 'NC'),
  ('Hickory', 'hickory-nc', 'NC'),
  ('Goldsboro', 'goldsboro-nc', 'NC'),
  ('Monroe', 'monroe-nc', 'NC'),
  ('Mooresville', 'mooresville-nc', 'NC'),
  ('Sanford', 'sanford-nc', 'NC'),
  ('Cary', 'cary-nc-2', 'NC'),
  ('Matthews', 'matthews-nc', 'NC'),
  ('Waxhaw', 'waxhaw-nc', 'NC'),
  ('Wake Forest', 'wake-forest-nc', 'NC'),
  ('Garner', 'garner-nc', 'NC'),
  ('Clayton', 'clayton-nc', 'NC'),
  ('Smithfield', 'smithfield-nc', 'NC'),
  ('Kinston', 'kinston-nc', 'NC'),
  ('New Bern', 'new-bern-nc', 'NC'),
  ('Elizabeth City', 'elizabeth-city-nc', 'NC'),
  ('Shelby', 'shelby-nc', 'NC'),
  ('Lexington', 'lexington-nc', 'NC'),
  ('Thomasville', 'thomasville-nc', 'NC'),
  ('Statesville', 'statesville-nc', 'NC'),
  ('Henderson', 'henderson-nc', 'NC'),
  ('Lumberton', 'lumberton-nc', 'NC'),
  ('Roanoke Rapids', 'roanoke-rapids-nc', 'NC'),
  ('Tarboro', 'tarboro-nc', 'NC'),
  ('Washington', 'washington-nc', 'NC'),
  -- North Dakota
  ('Fargo', 'fargo-nd', 'ND'),
  ('Bismarck', 'bismarck-nd', 'ND'),
  ('Grand Forks', 'grand-forks-nd', 'ND'),
  ('Minot', 'minot-nd', 'ND'),
  ('West Fargo', 'west-fargo-nd', 'ND'),
  ('Williston', 'williston-nd', 'ND'),
  ('Dickinson', 'dickinson-nd', 'ND'),
  ('Jamestown', 'jamestown-nd', 'ND'),
  ('Wahpeton', 'wahpeton-nd', 'ND'),
  ('Devils Lake', 'devils-lake-nd', 'ND'),
  ('Valley City', 'valley-city-nd', 'ND'),
  ('Mandan', 'mandan-nd', 'ND'),
  ('Beulah', 'beulah-nd', 'ND'),
  -- Ohio
  ('Columbus', 'columbus-oh', 'OH'),
  ('Cleveland', 'cleveland-oh', 'OH'),
  ('Cincinnati', 'cincinnati-oh', 'OH'),
  ('Toledo', 'toledo-oh', 'OH'),
  ('Akron', 'akron-oh', 'OH'),
  ('Dayton', 'dayton-oh', 'OH'),
  ('Parma', 'parma-oh', 'OH'),
  ('Canton', 'canton-oh', 'OH'),
  ('Youngstown', 'youngstown-oh', 'OH'),
  ('Lorain', 'lorain-oh', 'OH'),
  ('Hamilton', 'hamilton-oh', 'OH'),
  ('Springfield', 'springfield-oh', 'OH'),
  ('Kettering', 'kettering-oh', 'OH'),
  ('Elyria', 'elyria-oh', 'OH'),
  ('Lakewood', 'lakewood-oh', 'OH'),
  ('Cuyahoga Falls', 'cuyahoga-falls-oh', 'OH'),
  ('Middletown', 'middletown-oh', 'OH'),
  ('Mansfield', 'mansfield-oh', 'OH'),
  ('Mentor', 'mentor-oh', 'OH'),
  ('Beavercreek', 'beavercreek-oh', 'OH'),
  ('Newark', 'newark-oh', 'OH'),
  ('Marion', 'marion-oh', 'OH'),
  ('Zanesville', 'zanesville-oh', 'OH'),
  ('Findlay', 'findlay-oh', 'OH'),
  ('Lancaster', 'lancaster-oh', 'OH'),
  ('Chillicothe', 'chillicothe-oh', 'OH'),
  ('Sandusky', 'sandusky-oh', 'OH'),
  ('Ashtabula', 'ashtabula-oh', 'OH'),
  ('Delaware', 'delaware-oh', 'OH'),
  ('Westerville', 'westerville-oh', 'OH'),
  ('Dublin', 'dublin-oh', 'OH'),
  ('Hilliard', 'hilliard-oh', 'OH'),
  ('Grove City', 'grove-city-oh', 'OH'),
  ('Upper Arlington', 'upper-arlington-oh', 'OH'),
  ('Gahanna', 'gahanna-oh', 'OH'),
  ('Reynoldsburg', 'reynoldsburg-oh', 'OH'),
  ('Pickerington', 'pickerington-oh', 'OH'),
  ('Troy', 'troy-oh', 'OH'),
  ('Piqua', 'piqua-oh', 'OH'),
  ('Sidney', 'sidney-oh', 'OH'),
  ('Xenia', 'xenia-oh', 'OH'),
  ('Fairfield', 'fairfield-oh', 'OH'),
  ('Niles', 'niles-oh', 'OH'),
  ('Warren', 'warren-oh', 'OH'),
  ('Boardman', 'boardman-oh', 'OH'),
  ('Austintown', 'austintown-oh', 'OH'),
  ('Bowling Green', 'bowling-green-oh', 'OH'),
  ('Lima', 'lima-oh', 'OH'),
  ('Steubenville', 'steubenville-oh', 'OH'),
  ('Portsmouth', 'portsmouth-oh', 'OH'),
  ('Marietta', 'marietta-oh', 'OH'),
  ('Ironton', 'ironton-oh', 'OH'),
  ('Defiance', 'defiance-oh', 'OH'),
  ('Tiffin', 'tiffin-oh', 'OH'),
  ('Wooster', 'wooster-oh', 'OH'),
  ('Ashland', 'ashland-oh', 'OH'),
  ('Mount Vernon', 'mount-vernon-oh', 'OH'),
  ('Bellefontaine', 'bellefontaine-oh', 'OH'),
  ('Washington Court House', 'washington-court-house-oh', 'OH'),
  ('Wilmington', 'wilmington-oh', 'OH'),
  ('Bryan', 'bryan-oh', 'OH'),
  ('Van Wert', 'van-wert-oh', 'OH'),
  ('Wapakoneta', 'wapakoneta-oh', 'OH'),
  ('St. Marys', 'st-marys-oh', 'OH'),
  ('Celina', 'celina-oh', 'OH'),
  ('Napoleon', 'napoleon-oh', 'OH'),
  ('Perrysburg', 'perrysburg-oh', 'OH'),
  ('Maumee', 'maumee-oh', 'OH'),
  ('Sylvania', 'sylvania-oh', 'OH'),
  ('Oregon', 'oregon-oh', 'OH'),
  ('Northwood', 'northwood-oh', 'OH'),
  ('Rossford', 'rossford-oh', 'OH'),
  ('Walbridge', 'walbridge-oh', 'OH'),
  ('Haskins', 'haskins-oh', 'OH'),
  ('Luckey', 'luckey-oh', 'OH'),
  ('Pemberville', 'pemberville-oh', 'OH'),
  ('Bradner', 'bradner-oh', 'OH'),
  ('Risingsun', 'risingsun-oh', 'OH'),
  ('Wayne', 'wayne-oh', 'OH'),
  ('Custar', 'custar-oh', 'OH'),
  ('Weston', 'weston-oh', 'OH'),
  ('Grand Rapids', 'grand-rapids-oh', 'OH'),
  ('Tontogany', 'tontogany-oh', 'OH'),
  ('Portage', 'portage-oh', 'OH'),
  ('Milton Center', 'milton-center-oh', 'OH'),
  ('Rudolph', 'rudolph-oh', 'OH'),
  ('Bairdstown', 'bairdstown-oh', 'OH'),
  ('Jerry City', 'jerry-city-oh', 'OH'),
  ('Deshler', 'deshler-oh', 'OH'),
  ('Dunbridge', 'dunbridge-oh', 'OH'),
  ('West Millgrove', 'west-millgrove-oh', 'OH'),
  ('McClure', 'mcclure-oh', 'OH'),
  ('Malinta', 'malinta-oh', 'OH'),
  ('Hamler', 'hamler-oh', 'OH'),
  ('Colton', 'colton-oh', 'OH'),
  ('Okolona', 'okolona-oh', 'OH'),
  ('Tennessee', 'tennessee-oh', 'OH'),
  ('Neapolis', 'neapolis-oh', 'OH'),
  -- Oklahoma
  ('Oklahoma City', 'oklahoma-city-ok', 'OK'),
  ('Tulsa', 'tulsa-ok', 'OK'),
  ('Norman', 'norman-ok', 'OK'),
  ('Broken Arrow', 'broken-arrow-ok', 'OK'),
  ('Lawton', 'lawton-ok', 'OK'),
  ('Edmond', 'edmond-ok', 'OK'),
  ('Moore', 'moore-ok', 'OK'),
  ('Midwest City', 'midwest-city-ok', 'OK'),
  ('Enid', 'enid-ok', 'OK'),
  ('Stillwater', 'stillwater-ok', 'OK'),
  ('Muskogee', 'muskogee-ok', 'OK'),
  ('Bartlesville', 'bartlesville-ok', 'OK'),
  ('Owasso', 'owasso-ok', 'OK'),
  ('Shawnee', 'shawnee-ok', 'OK'),
  ('Altus', 'altus-ok', 'OK'),
  ('Ponca City', 'ponca-city-ok', 'OK'),
  ('Ardmore', 'ardmore-ok', 'OK'),
  ('Duncan', 'duncan-ok', 'OK'),
  ('Sand Springs', 'sand-springs-ok', 'OK'),
  ('Sapulpa', 'sapulpa-ok', 'OK'),
  -- Oregon
  ('Portland', 'portland-or', 'OR'),
  ('Salem', 'salem-or', 'OR'),
  ('Eugene', 'eugene-or', 'OR'),
  ('Gresham', 'gresham-or', 'OR'),
  ('Hillsboro', 'hillsboro-or', 'OR'),
  ('Beaverton', 'beaverton-or', 'OR'),
  ('Bend', 'bend-or', 'OR'),
  ('Medford', 'medford-or', 'OR'),
  ('Springfield', 'springfield-or', 'OR'),
  ('Corvallis', 'corvallis-or', 'OR'),
  ('Albany', 'albany-or', 'OR'),
  ('Tigard', 'tigard-or', 'OR'),
  ('Lake Oswego', 'lake-oswego-or', 'OR'),
  ('Keizer', 'keizer-or', 'OR'),
  ('Grants Pass', 'grants-pass-or', 'OR'),
  ('Oregon City', 'oregon-city-or', 'OR'),
  ('McMinnville', 'mcminnville-or', 'OR'),
  ('Redmond', 'redmond-or', 'OR'),
  ('Tualatin', 'tualatin-or', 'OR'),
  ('West Linn', 'west-linn-or', 'OR'),
  -- Pennsylvania
  ('Philadelphia', 'philadelphia', 'PA'),
  ('Pittsburgh', 'pittsburgh-pa', 'PA'),
  ('Allentown', 'allentown-pa', 'PA'),
  ('Erie', 'erie-pa', 'PA'),
  ('Reading', 'reading-pa', 'PA'),
  ('Scranton', 'scranton-pa', 'PA'),
  ('Bethlehem', 'bethlehem-pa', 'PA'),
  ('Lancaster', 'lancaster-pa', 'PA'),
  ('Harrisburg', 'harrisburg-pa', 'PA'),
  ('York', 'york-pa', 'PA'),
  ('State College', 'state-college-pa', 'PA'),
  ('Altoona', 'altoona-pa', 'PA'),
  ('Wilkes-Barre', 'wilkes-barre-pa', 'PA'),
  ('Chester', 'chester-pa', 'PA'),
  ('Williamsport', 'williamsport-pa', 'PA'),
  ('Easton', 'easton-pa', 'PA'),
  ('Lebanon', 'lebanon-pa', 'PA'),
  ('Hazleton', 'hazleton-pa', 'PA'),
  ('New Castle', 'new-castle-pa', 'PA'),
  ('McKeesport', 'mckeesport-pa', 'PA'),
  ('Johnstown', 'johnstown-pa', 'PA'),
  ('Pottsville', 'pottsville-pa', 'PA'),
  ('Coatesville', 'coatesville-pa', 'PA'),
  ('Nanticoke', 'nanticoke-pa', 'PA'),
  ('Uniontown', 'uniontown-pa', 'PA'),
  ('Chambersburg', 'chambersburg-pa', 'PA'),
  ('Sunbury', 'sunbury-pa', 'PA'),
  ('Lock Haven', 'lock-haven-pa', 'PA'),
  ('Bradford', 'bradford-pa', 'PA'),
  ('DuBois', 'dubois-pa', 'PA'),
  ('Carbondale', 'carbondale-pa', 'PA'),
  ('St. Marys', 'st-marys-pa', 'PA'),
  ('Parker', 'parker-pa', 'PA'),
  ('Warren', 'warren-pa', 'PA'),
  ('Meadville', 'meadville-pa', 'PA'),
  ('Titusville', 'titusville-pa', 'PA'),
  ('Greensburg', 'greensburg-pa', 'PA'),
  ('Washington', 'washington-pa', 'PA'),
  ('Uniontown', 'uniontown-pa-2', 'PA'),
  ('Monessen', 'monessen-pa', 'PA'),
  ('Latrobe', 'latrobe-pa', 'PA'),
  ('Canonsburg', 'canonsburg-pa', 'PA'),
  ('Carnegie', 'carnegie-pa', 'PA'),
  ('Coraopolis', 'coraopolis-pa', 'PA'),
  ('McKees Rocks', 'mckees-rocks-pa', 'PA'),
  ('Sewickley', 'sewickley-pa', 'PA'),
  ('Oakmont', 'oakmont-pa', 'PA'),
  ('Verona', 'verona-pa', 'PA'),
  ('Aspinwall', 'aspinwall-pa', 'PA'),
  ('Sharpsburg', 'sharpsburg-pa', 'PA'),
  ('Etna', 'etna-pa', 'PA'),
  ('Millvale', 'millvale-pa', 'PA'),
  ('Bellevue', 'bellevue-pa', 'PA'),
  ('Avalon', 'avalon-pa', 'PA'),
  ('Ben Avon', 'ben-avon-pa', 'PA'),
  ('Emsworth', 'emsworth-pa', 'PA'),
  ('Kilbuck', 'kilbuck-pa', 'PA'),
  ('Leetsdale', 'leetsdale-pa', 'PA'),
  ('Edgeworth', 'edgeworth-pa', 'PA'),
  ('Sewickley Heights', 'sewickley-heights-pa', 'PA'),
  ('Glen Osborne', 'glen-osborne-pa', 'PA'),
  ('Haysville', 'haysville-pa', 'PA'),
  ('Glenfield', 'glenfield-pa', 'PA'),
  ('Ohioville', 'ohioville-pa', 'PA'),
  ('Ambridge', 'ambridge-pa', 'PA'),
  ('Baden', 'baden-pa', 'PA'),
  ('Conway', 'conway-pa', 'PA'),
  ('Freedom', 'freedom-pa', 'PA'),
  ('Monaca', 'monaca-pa', 'PA'),
  ('Rochester', 'rochester-pa', 'PA'),
  ('Shippingport', 'shippingport-pa', 'PA'),
  ('South Heights', 'south-heights-pa', 'PA'),
  ('Vanport', 'vanport-pa', 'PA'),
  ('West Mayfield', 'west-mayfield-pa', 'PA'),
  ('Homewood', 'homewood-pa', 'PA'),
  ('Koppel', 'koppel-pa', 'PA'),
  ('Big Beaver', 'big-beaver-pa', 'PA'),
  ('Beaver Falls', 'beaver-falls-pa', 'PA'),
  ('Chippewa Township', 'chippewa-township-pa', 'PA'),
  ('Patterson Township', 'patterson-township-pa', 'PA'),
  ('Brighton Township', 'brighton-township-pa', 'PA'),
  ('Center Township', 'center-township-pa', 'PA'),
  ('Industry', 'industry-pa', 'PA'),
  ('Midland', 'midland-pa', 'PA'),
  ('Potter Township', 'potter-township-pa', 'PA'),
  ('Raccoon Township', 'raccoon-township-pa', 'PA'),
  ('Franklin Springs', 'franklin-springs-pa', 'PA'),
  ('Darlington', 'darlington-pa', 'PA'),
  ('Enon Valley', 'enon-valley-pa', 'PA'),
  ('New Galilee', 'new-galilee-pa', 'PA'),
  ('Bige Run', 'bige-run-pa', 'PA'),
  ('Blossburg', 'blossburg-pa', 'PA'),
  ('Brockway', 'brockway-pa', 'PA'),
  ('Brookville', 'brookville-pa', 'PA'),
  ('Coudersport', 'coudersport-pa', 'PA'),
  ('Emporium', 'emporium-pa', 'PA'),
  ('Galeton', 'galeton-pa', 'PA'),
  ('Mansfield', 'mansfield-pa', 'PA'),
  ('Port Allegany', 'port-allegany-pa', 'PA'),
  ('Roulette', 'roulette-pa', 'PA'),
  ('Smethport', 'smethport-pa', 'PA'),
  ('Towanda', 'towanda-pa', 'PA'),
  ('Wellsboro', 'wellsboro-pa', 'PA'),
  -- Rhode Island
  ('Providence', 'providence-ri', 'RI'),
  ('Warwick', 'warwick-ri', 'RI'),
  ('Cranston', 'cranston-ri', 'RI'),
  ('Pawtucket', 'pawtucket-ri', 'RI'),
  ('East Providence', 'east-providence-ri', 'RI'),
  ('Woonsocket', 'woonsocket-ri', 'RI'),
  ('Coventry', 'coventry-ri', 'RI'),
  ('Cumberland', 'cumberland-ri', 'RI'),
  ('North Providence', 'north-providence-ri', 'RI'),
  ('South Kingstown', 'south-kingstown-ri', 'RI'),
  ('Westerly', 'westerly-ri', 'RI'),
  ('Smithfield', 'smithfield-ri', 'RI'),
  ('Bristol', 'bristol-ri', 'RI'),
  ('Lincoln', 'lincoln-ri', 'RI'),
  ('Newport', 'newport-ri', 'RI'),
  -- South Carolina
  ('Charleston', 'charleston-sc', 'SC'),
  ('Columbia', 'columbia-sc', 'SC'),
  ('North Charleston', 'north-charleston-sc', 'SC'),
  ('Mount Pleasant', 'mount-pleasant-sc', 'SC'),
  ('Rock Hill', 'rock-hill-sc', 'SC'),
  ('Greenville', 'greenville-sc', 'SC'),
  ('Summerville', 'summerville-sc', 'SC'),
  ('Sumter', 'sumter-sc', 'SC'),
  ('Goose Creek', 'goose-creek-sc', 'SC'),
  ('Hilton Head Island', 'hilton-head-island-sc', 'SC'),
  ('Florence', 'florence-sc', 'SC'),
  ('Spartanburg', 'spartanburg-sc', 'SC'),
  ('Myrtle Beach', 'myrtle-beach-sc', 'SC'),
  ('Anderson', 'anderson-sc', 'SC'),
  ('Greer', 'greer-sc', 'SC'),
  ('Aiken', 'aiken-sc', 'SC'),
  ('Beaufort', 'beaufort-sc', 'SC'),
  ('Mauldin', 'mauldin-sc', 'SC'),
  ('Greenwood', 'greenwood-sc', 'SC'),
  ('Easley', 'easley-sc', 'SC'),
  ('Simpsonville', 'simpsonville-sc', 'SC'),
  ('Lexington', 'lexington-sc', 'SC'),
  ('Conway', 'conway-sc', 'SC'),
  ('Clemson', 'clemson-sc', 'SC'),
  ('Seneca', 'seneca-sc', 'SC'),
  ('Orangeburg', 'orangeburg-sc', 'SC'),
  -- South Dakota
  ('Sioux Falls', 'sioux-falls-sd', 'SD'),
  ('Rapid City', 'rapid-city-sd', 'SD'),
  ('Pierre', 'pierre-sd', 'SD'),
  ('Brookings', 'brooking-sd', 'SD'),
  ('Brandon', 'brandon-sd', 'SD'),
  ('Watertown', 'watertown-sd', 'SD'),
  ('Mitchell', 'mitchell-sd', 'SD'),
  ('Yankton', 'yankton-sd', 'SD'),
  ('Vermillion', 'vermillion-sd', 'SD'),
  ('Huron', 'huron-sd', 'SD'),
  ('Aberdeen', 'aberdeen-sd', 'SD'),
  ('Sturgis', 'sturgis-sd', 'SD'),
  ('Spearfish', 'spearfish-sd', 'SD'),
  ('Madison', 'madison-sd', 'SD'),
  -- Tennessee
  ('Nashville', 'nashville-tn', 'TN'),
  ('Memphis', 'memphis-tn', 'TN'),
  ('Knoxville', 'knoxville-tn', 'TN'),
  ('Chattanooga', 'chattanooga-tn', 'TN'),
  ('Clarksville', 'clarksville-tn', 'TN'),
  ('Murfreesboro', 'murfreesboro-tn', 'TN'),
  ('Franklin', 'franklin-tn', 'TN'),
  ('Jackson', 'jackson-tn', 'TN'),
  ('Johnson City', 'johnson-city-tn', 'TN'),
  ('Bartlett', 'bartlett-tn', 'TN'),
  ('Hendersonville', 'hendersonville-tn', 'TN'),
  ('Kingsport', 'kingsport-tn', 'TN'),
  ('Collierville', 'collierville-tn', 'TN'),
  ('Cleveland', 'cleveland-tn', 'TN'),
  ('Smyrna', 'smyrna-tn', 'TN'),
  ('Germantown', 'germantown-tn', 'TN'),
  ('Brentwood', 'brentwood-tn', 'TN'),
  ('Cookeville', 'cookeville-tn', 'TN'),
  ('Oak Ridge', 'oak-ridge-tn', 'TN'),
  ('Maryville', 'maryville-tn', 'TN'),
  -- Texas
  ('Houston', 'houston', 'TX'),
  ('San Antonio', 'san-antonio-tx', 'TX'),
  ('Dallas', 'dallas-tx', 'TX'),
  ('Austin', 'austin-tx', 'TX'),
  ('Fort Worth', 'fort-worth-tx', 'TX'),
  ('El Paso', 'el-paso-tx', 'TX'),
  ('Arlington', 'arlington-tx', 'TX'),
  ('Corpus Christi', 'corpus-christi-tx', 'TX'),
  ('Plano', 'plano-tx', 'TX'),
  ('Lubbock', 'lubbock-tx', 'TX'),
  ('Laredo', 'laredo-tx', 'TX'),
  ('Garland', 'garland-tx', 'TX'),
  ('Irving', 'irving-tx', 'TX'),
  ('Frisco', 'frisco-tx', 'TX'),
  ('Amarillo', 'amarillo-tx', 'TX'),
  ('Grand Prairie', 'grand-prairie-tx', 'TX'),
  ('McKinney', 'mckinney-tx', 'TX'),
  ('McAllen', 'mcallen-tx', 'TX'),
  ('Brownsville', 'brownsville-tx', 'TX'),
  ('Killeen', 'killeen-tx', 'TX'),
  ('Pasadena', 'pasadena-tx', 'TX'),
  ('Mesquite', 'mesquite-tx', 'TX'),
  ('Denton', 'denton-tx', 'TX'),
  ('Midland', 'midland-tx', 'TX'),
  ('Lewisville', 'lewisville-tx', 'TX'),
  ('Richardson', 'richardson-tx', 'TX'),
  ('Pearland', 'pearland-tx', 'TX'),
  ('Abilene', 'abilene-tx', 'TX'),
  ('Round Rock', 'round-rock-tx', 'TX'),
  ('College Station', 'college-station-tx', 'TX'),
  ('Allen', 'allen-tx', 'TX'),
  ('Carrollton', 'carrollton-tx', 'TX'),
  ('Waco', 'waco-tx', 'TX'),
  ('Wichita Falls', 'wichita-falls-tx', 'TX'),
  ('Beaumont', 'beaumont-tx', 'TX'),
  ('Odessa', 'odessa-tx', 'TX'),
  ('San Angelo', 'san-angelo-tx', 'TX'),
  ('Sugar Land', 'sugar-land-tx', 'TX')
  ,('Spring', 'spring-tx', 'TX'),
  ('League City', 'league-city-tx', 'TX'),
  ('Longview', 'longview-tx', 'TX'),
  ('Edinburg', 'edinburg-tx', 'TX'),
  ('Conroe', 'conroe-tx', 'TX'),
  ('Missouri City', 'missouri-city-tx', 'TX'),
  ('Mansfield', 'mansfield-tx', 'TX'),
  ('Cedar Park', 'cedar-park-tx', 'TX'),
  ('San Marcos', 'san-marcos-tx', 'TX'),
  ('DeSoto', 'desoto-tx', 'TX'),
  ('Harlingen', 'harlingen-tx', 'TX'),
  ('Pflugerville', 'pflugerville-tx', 'TX'),
  ('North Richland Hills', 'north-richland-hills-tx', 'TX'),
  ('Georgetown', 'georgetown-tx', 'TX'),
  ('New Braunfels', 'new-braunfels-tx', 'TX'),
  ('Rowlett', 'rowlett-tx', 'TX'),
  ('Flower Mound', 'flower-mound-tx', 'TX'),
  ('Rockwall', 'rockwall-tx', 'TX'),
  ('Katy', 'katy-tx', 'TX'),
  ('Burleson', 'burleson-tx', 'TX'),
  ('Coppell', 'coppell-tx', 'TX'),
  ('Southlake', 'southlake-tx', 'TX'),
  ('Grapevine', 'grapevine-tx', 'TX'),
  ('Colleyville', 'colleyville-tx', 'TX'),
  ('Bedford', 'bedford-tx', 'TX'),
  ('Euless', 'euless-tx', 'TX'),
  ('Hurst', 'hurst-tx', 'TX'),
  ('North Richland Hills', 'north-richland-hills-tx-2', 'TX'),
  ('Richland Hills', 'richland-hills-tx', 'TX'),
  ('Watauga', 'watauga-tx', 'TX'),
  ('Haltom City', 'haltom-city-tx', 'TX'),
  ('Keller', 'keller-tx', 'TX'),
  ('Trophy Club', 'trophy-club-tx', 'TX'),
  ('Roanoke', 'roanoke-tx', 'TX'),
  ('Westlake', 'westlake-tx', 'TX'),
  ('Riverside', 'riverside-tx', 'TX'),
  ('Azle', 'azle-tx', 'TX'),
  ('Saginaw', 'saginaw-tx', 'TX'),
  ('Eagle Mountain', 'eagle-mountain-tx', 'TX'),
  ('White Settlement', 'white-settlement-tx', 'TX'),
  ('Forest Hill', 'forest-hill-tx', 'TX'),
  ('Everman', 'everman-tx', 'TX'),
  ('Crowley', 'crowley-tx', 'TX'),
  ('Burleson', 'burleson-tx-2', 'TX'),
  ('Joshua', 'joshua-tx', 'TX'),
  ('Cleburne', 'cleburne-tx', 'TX'),
  ('Alvarado', 'alvarado-tx', 'TX'),
  ('Venus', 'venus-tx', 'TX'),
  ('Keene', 'keene-tx', 'TX'),
  ('Rio Vista', 'rio-vista-tx', 'TX'),
  ('Godley', 'godley-tx', 'TX'),
  ('Lillian', 'lillian-tx', 'TX'),
  ('Briaroaks', 'briaroaks-tx', 'TX'),
  ('Covington', 'covington-tx', 'TX'),
  ('Grandview', 'grandview-tx', 'TX'),
  ('Crescent', 'crescent-tx', 'TX'),
  ('Bardwell', 'bardwell-tx', 'TX'),
  ('Ennis', 'ennis-tx', 'TX'),
  ('Waxahachie', 'waxahachie-tx', 'TX'),
  ('Midlothian', 'midlothian-tx', 'TX'),
  ('Red Oak', 'red-oak-tx', 'TX'),
  ('Glenn Heights', 'glenn-heights-tx', 'TX'),
  ('Ovilla', 'ovilla-tx', 'TX'),
  ('DeSoto', 'desoto-tx-2', 'TX'),
  ('Lancaster', 'lancaster-tx', 'TX'),
  ('Hutchins', 'hutchins-tx', 'TX'),
  ('Wilmer', 'wilmer-tx', 'TX'),
  ('Seagoville', 'seagoville-tx', 'TX'),
  ('Combine', 'combine-tx', 'TX'),
  ('Crandall', 'crandall-tx', 'TX'),
  ('Kaufman', 'kaufman-tx', 'TX'),
  ('Terrell', 'terrell-tx', 'TX'),
  ('Talty', 'talty-tx', 'TX'),
  ('Forney', 'forney-tx', 'TX'),
  ('Sunnyvale', 'sunnyvale-tx', 'TX'),
  ('Mesquite', 'mesquite-tx-2', 'TX'),
  ('Balch Springs', 'balch-springs-tx', 'TX'),
  ('Garland', 'garland-tx-2', 'TX'),
  ('Rowlett', 'rowlett-tx-2', 'TX'),
  ('Sachse', 'sachse-tx', 'TX'),
  ('Wylie', 'wylie-tx', 'TX'),
  ('St. Paul', 'st-paul-tx', 'TX'),
  ('Lavon', 'lavon-tx', 'TX'),
  ('Nevada', 'nevada-tx', 'TX'),
  ('Josephine', 'josephine-tx', 'TX'),
  ('Royse City', 'royse-city-tx', 'TX'),
  ('Caddo Mills', 'caddo-mills-tx', 'TX'),
  ('Greenville', 'greenville-tx', 'TX'),
  ('Commerce', 'commerce-tx', 'TX'),
  ('Wolfe City', 'wolfe-city-tx', 'TX'),
  ('Quinlan', 'quinlan-tx', 'TX'),
  ('Hawk Cove', 'hawk-cove-tx', 'TX'),
  ('West Tawakoni', 'west-tawakoni-tx', 'TX'),
  ('East Tawakoni', 'east-tawakoni-tx', 'TX'),
  ('Wills Point', 'wills-point-tx', 'TX'),
  ('Canton', 'canton-tx', 'TX'),
  ('Edgewood', 'edgewood-tx', 'TX'),
  ('Van', 'van-tx', 'TX'),
  ('Grand Saline', 'grand-saline-tx', 'TX'),
  ('Emory', 'emory-tx', 'TX'),
  ('Point', 'point-tx', 'TX'),
  ('Easton', 'easton-tx', 'TX'),
  ('Overton', 'overton-tx', 'TX'),
  ('Arp', 'arp-tx', 'TX'),
  ('Troup', 'troup-tx', 'TX'),
  ('Whitehouse', 'whitehouse-tx', 'TX'),
  ('Bullard', 'bullard-tx', 'TX'),
  ('Lake Jackson', 'lake-jackson-tx', 'TX'),
  ('Jacksonville', 'jacksonville-tx', 'TX'),
  ('Rusk', 'rusk-tx', 'TX'),
  ('Alto', 'alto-tx', 'TX'),
  ('Reklaw', 'reklaw-tx', 'TX'),
  ('Cushing', 'cushing-tx', 'TX'),
  ('Nacogdoches', 'nacogdoches-tx', 'TX'),
  ('Lufkin', 'lufkin-tx', 'TX'),
  ('Hudson', 'hudson-tx', 'TX'),
  ('Diboll', 'diboll-tx', 'TX'),
  ('Burke', 'burke-tx', 'TX'),
  ('Huntington', 'huntington-tx', 'TX'),
  ('Wells', 'wells-tx', 'TX'),
  ('Cushing', 'cushing-tx-2', 'TX'),
  ('Alto', 'alto-tx-2', 'TX'),
  ('Douglass', 'douglass-tx', 'TX'),
  ('Mount Enterprise', 'mount-enterprise-tx', 'TX'),
  ('Carlton', 'carlton-tx', 'TX'),
  ('Goodrich', 'goodrich-tx', 'TX'),
  ('Leggett', 'leggett-tx', 'TX'),
  ('Onalaska', 'onalaska-tx', 'TX'),
  ('Livingston', 'livingston-tx', 'TX'),
  ('Coldspring', 'coldspring-tx', 'TX'),
  ('Shepherd', 'shepherd-tx', 'TX'),
  ('New Waverly', 'new-waverly-tx', 'TX'),
  ('Huntsville', 'huntsville-tx', 'TX'),
  ('Trinity', 'trinity-tx', 'TX'),
  ('Anderson', 'anderson-tx', 'TX'),
  ('Bedias', 'bedias-tx', 'TX'),
  ('Iola', 'iola-tx', 'TX'),
  ('North Zulch', 'north-zulch-tx', 'TX'),
  ('Madisonville', 'madisonville-tx', 'TX'),
  ('Midway', 'midway-tx', 'TX'),
  ('Centerville', 'centerville-tx', 'TX'),
  ('Leona', 'leona-tx', 'TX'),
  ('Buffalo', 'buffalo-tx', 'TX'),
  ('Oakwood', 'oakwood-tx', 'TX'),
  ('Fairfield', 'fairfield-tx', 'TX'),
  ('Teague', 'teague-tx', 'TX'),
  ('Freestone', 'freestone-tx', 'TX'),
  ('Wortham', 'wortham-tx', 'TX'),
  ('Kirvin', 'kirvin-tx', 'TX'),
  ('Donie', 'donie-tx', 'TX'),
  ('Streetman', 'streetman-tx', 'TX'),
  ('Mexia', 'mexia-tx', 'TX'),
  ('Coolidge', 'coolidge-tx', 'TX'),
  ('Groesbeck', 'groesbeck-tx', 'TX'),
  ('Thornton', 'thornton-tx', 'TX'),
  ('Kosse', 'kosse-tx', 'TX'),
  ('Mart', 'mart-tx', 'TX'),
  ('McGregor', 'mcgregor-tx', 'TX'),
  ('Leroy', 'leroy-tx', 'TX'),
  ('West', 'west-tx', 'TX'),
  ('Hillsboro', 'hillsboro-tx', 'TX'),
  ('Hubbard', 'hubbard-tx', 'TX'),
  ('Penelope', 'penelope-tx', 'TX'),
  ('Birome', 'birome-tx', 'TX'),
  ('Braham', 'braham-tx', 'TX'),
  ('Bynum', 'bynum-tx', 'TX'),
  ('Covington', 'covington-tx-2', 'TX'),
  ('Itasca', 'itasca-tx', 'TX'),
  ('Grandview', 'grandview-tx-2', 'TX'),
  ('Venus', 'venus-tx-2', 'TX'),
  ('Alvarado', 'alvarado-tx-2', 'TX'),
  ('Lillian', 'lillian-tx-2', 'TX'),
  ('Briaroaks', 'briaroaks-tx-2', 'TX'),
  ('Covington', 'covington-tx-3', 'TX'),
  ('Grandview', 'grandview-tx-3', 'TX'),
  ('Crescent', 'crescent-tx-2', 'TX'),
  ('Bardwell', 'bardwell-tx-2', 'TX'),
  ('Ennis', 'ennis-tx-2', 'TX'),
  ('Waxahachie', 'waxahachie-tx-2', 'TX'),
  ('Midlothian', 'midlothian-tx-2', 'TX'),
  ('Red Oak', 'red-oak-tx-2', 'TX'),
  ('Glenn Heights', 'glenn-heights-tx-2', 'TX'),
  ('Ovilla', 'ovilla-tx-2', 'TX'),
  ('DeSoto', 'desoto-tx-3', 'TX'),
  ('Lancaster', 'lancaster-tx-2', 'TX'),
  ('Hutchins', 'hutchins-tx-2', 'TX'),
  ('Wilmer', 'wilmer-tx-2', 'TX'),
  ('Seagoville', 'seagoville-tx-2', 'TX'),
  ('Combine', 'combine-tx-2', 'TX'),
  ('Crandall', 'crandall-tx-2', 'TX'),
  ('Kaufman', 'kaufman-tx-2', 'TX'),
  ('Terrell', 'terrell-tx-2', 'TX'),
  ('Talty', 'talty-tx-2', 'TX'),
  ('Forney', 'forney-tx-2', 'TX'),
  ('Sunnyvale', 'sunnyvale-tx-2', 'TX'),
  ('Mesquite', 'mesquite-tx-3', 'TX'),
  ('Balch Springs', 'balch-springs-tx-2', 'TX'),
  ('Garland', 'garland-tx-3', 'TX'),
  ('Rowlett', 'rowlett-tx-3', 'TX'),
  ('Sachse', 'sachse-tx-2', 'TX'),
  ('Wylie', 'wylie-tx-2', 'TX'),
  ('St. Paul', 'st-paul-tx-2', 'TX'),
  ('Lavon', 'lavon-tx-2', 'TX'),
  ('Nevada', 'nevada-tx-2', 'TX'),
  ('Josephine', 'josephine-tx-2', 'TX'),
  ('Royse City', 'royse-city-tx-2', 'TX'),
  ('Caddo Mills', 'caddo-mills-tx-2', 'TX'),
  ('Greenville', 'greenville-tx-2', 'TX'),
  ('Commerce', 'commerce-tx-2', 'TX'),
  ('Wolfe City', 'wolfe-city-tx-2', 'TX'),
  ('Quinlan', 'quinlan-tx-2', 'TX'),
  ('Hawk Cove', 'hawk-cove-tx-2', 'TX'),
  ('West Tawakoni', 'west-tawakoni-tx-2', 'TX'),
  ('East Tawakoni', 'east-tawakoni-tx-2', 'TX'),
  ('Wills Point', 'wills-point-tx-2', 'TX'),
  ('Canton', 'canton-tx-2', 'TX'),
  ('Edgewood', 'edgewood-tx-2', 'TX'),
  ('Van', 'van-tx-2', 'TX'),
  ('Grand Saline', 'grand-saline-tx-2', 'TX'),
  ('Emory', 'emory-tx-2', 'TX'),
  ('Point', 'point-tx-2', 'TX'),
  ('Easton', 'easton-tx-2', 'TX'),
  ('Overton', 'overton-tx-2', 'TX'),
  ('Arp', 'arp-tx-2', 'TX'),
  ('Troup', 'troup-tx-2', 'TX'),
  ('Whitehouse', 'whitehouse-tx-2', 'TX'),
  ('Bullard', 'bullard-tx-2', 'TX'),
  ('Lake Jackson', 'lake-jackson-tx-2', 'TX'),
  ('Jacksonville', 'jacksonville-tx-2', 'TX'),
  ('Rusk', 'rusk-tx-2', 'TX'),
  ('Alto', 'alto-tx-3', 'TX'),
  ('Reklaw', 'reklaw-tx-2', 'TX'),
  ('Cushing', 'cushing-tx-3', 'TX'),
  ('Nacogdoches', 'nacogdoches-tx-2', 'TX'),
  ('Lufkin', 'lufkin-tx-2', 'TX'),
  ('Hudson', 'hudson-tx-2', 'TX'),
  ('Diboll', 'diboll-tx-2', 'TX'),
  ('Burke', 'burke-tx-2', 'TX'),
  ('Huntington', 'huntington-tx-2', 'TX'),
  ('Wells', 'wells-tx-2', 'TX'),
  ('Cushing', 'cushing-tx-4', 'TX'),
  ('Alto', 'alto-tx-4', 'TX'),
  ('Douglass', 'douglass-tx-2', 'TX'),
  ('Mount Enterprise', 'mount-enterprise-tx-2', 'TX'),
  ('Carlton', 'carlton-tx-2', 'TX'),
  ('Goodrich', 'goodrich-tx-2', 'TX'),
  ('Leggett', 'leggett-tx-2', 'TX'),
  ('Onalaska', 'onalaska-tx-2', 'TX'),
  ('Livingston', 'livingston-tx-2', 'TX'),
  ('Coldspring', 'coldspring-tx-2', 'TX'),
  ('Shepherd', 'shepherd-tx-2', 'TX'),
  ('New Waverly', 'new-waverly-tx-2', 'TX'),
  ('Huntsville', 'huntsville-tx-2', 'TX'),
  ('Trinity', 'trinity-tx-2', 'TX'),
  ('Anderson', 'anderson-tx-2', 'TX'),
  ('Bedias', 'bedias-tx-2', 'TX'),
  ('Iola', 'iola-tx-2', 'TX'),
  ('North Zulch', 'north-zulch-tx-2', 'TX'),
  ('Madisonville', 'madisonville-tx-2', 'TX'),
  ('Midway', 'midway-tx-2', 'TX'),
  ('Centerville', 'centerville-tx-2', 'TX'),
  ('Leona', 'leona-tx-2', 'TX'),
  ('Buffalo', 'buffalo-tx-2', 'TX'),
  ('Oakwood', 'oakwood-tx-2', 'TX'),
  ('Fairfield', 'fairfield-tx-2', 'TX'),
  ('Teague', 'teague-tx-2', 'TX'),
  ('Freestone', 'freestone-tx-2', 'TX'),
  ('Wortham', 'wortham-tx-2', 'TX'),
  ('Kirvin', 'kirvin-tx-2', 'TX'),
  ('Donie', 'donie-tx-2', 'TX'),
  ('Streetman', 'streetman-tx-2', 'TX'),
  ('Mexia', 'mexia-tx-2', 'TX'),
  ('Coolidge', 'coolidge-tx-2', 'TX'),
  ('Groesbeck', 'groesbeck-tx-2', 'TX'),
  ('Thornton', 'thornton-tx-2', 'TX'),
  ('Kosse', 'kosse-tx-2', 'TX'),
  ('Mart', 'mart-tx-2', 'TX'),
  ('McGregor', 'mcgregor-tx-2', 'TX'),
  ('Leroy', 'leroy-tx-2', 'TX'),
  ('West', 'west-tx-2', 'TX'),
  ('Hillsboro', 'hillsboro-tx-2', 'TX'),
  ('Hubbard', 'hubbard-tx-2', 'TX'),
  ('Penelope', 'penelope-tx-2', 'TX'),
  ('Birome', 'birome-tx-2', 'TX'),
  ('Braham', 'braham-tx-2', 'TX'),
  ('Bynum', 'bynum-tx-2', 'TX'),
  ('Covington', 'covington-tx-4', 'TX'),
  ('Itasca', 'itasca-tx-2', 'TX'),
  -- Utah
  ('Salt Lake City', 'salt-lake-city-ut', 'UT'),
  ('West Valley City', 'west-valley-city-ut', 'UT'),
  ('Provo', 'provo-ut', 'UT'),
  ('West Jordan', 'west-jordan-ut', 'UT'),
  ('Orem', 'orem-ut', 'UT'),
  ('Sandy', 'sandy-ut', 'UT'),
  ('Ogden', 'ogden-ut', 'UT'),
  ('St. George', 'st-george-ut', 'UT'),
  ('Layton', 'layton-ut', 'UT'),
  ('South Jordan', 'south-jordan-ut', 'UT'),
  ('Lehi', 'lehi-ut', 'UT'),
  ('Millcreek', 'millcreek-ut', 'UT'),
  ('Murray', 'murray-ut', 'UT'),
  ('Draper', 'draper-ut', 'UT'),
  ('Spanish Fork', 'spanish-fork-ut', 'UT'),
  ('Taylorville', 'taylorville-ut', 'UT'),
  ('Bountiful', 'bountiful-ut', 'UT'),
  ('Riverton', 'riverton-ut', 'UT'),
  ('Tooele', 'tooele-ut', 'UT'),
  ('Roy', 'roy-ut', 'UT'),
  -- Vermont
  ('Burlington', 'burlington-vt', 'VT'),
  ('South Burlington', 'south-burlington-vt', 'VT'),
  ('Rutland', 'rutland-vt', 'VT'),
  ('Essex Junction', 'essex-junction-vt', 'VT'),
  ('Bennington', 'bennington-vt', 'VT'),
  ('Brattleboro', 'brattleboro-vt', 'VT'),
  ('Hartford', 'hartford-vt', 'VT'),
  ('Milton', 'milton-vt', 'VT'),
  ('Barre', 'barre-vt', 'VT'),
  ('Montpelier', 'montpelier-vt', 'VT'),
  ('St. Johnsbury', 'st-johnsbury-vt', 'VT'),
  ('St. Albans', 'st-albans-vt', 'VT'),
  ('Middlebury', 'middlebury-vt', 'VT'),
  ('Springfield', 'springfield-vt', 'VT'),
  -- Virginia
  ('Virginia Beach', 'virginia-beach-va', 'VA'),
  ('Norfolk', 'norfolk-va', 'VA'),
  ('Chesapeake', 'chesapeake-va', 'VA'),
  ('Richmond', 'richmond-va', 'VA'),
  ('Newport News', 'newport-news-va', 'VA'),
  ('Alexandria', 'alexandria-va', 'VA'),
  ('Hampton', 'hampton-va', 'VA'),
  ('Roanoke', 'roanoke-va', 'VA'),
  ('Portsmouth', 'portsmouth-va', 'VA'),
  ('Suffolk', 'suffolk-va', 'VA'),
  ('Lynchburg', 'lynchburg-va', 'VA'),
  ('Harrisonburg', 'harrisonburg-va', 'VA'),
  ('Charlottesville', 'charlottesville-va', 'VA'),
  ('Danville', 'danville-va', 'VA'),
  ('Manassas', 'manassas-va', 'VA'),
  ('Petersburg', 'petersburg-va', 'VA'),
  ('Fredericksburg', 'fredericksburg-va', 'VA'),
  ('Winchester', 'winchester-va', 'VA'),
  ('Salem', 'salem-va', 'VA'),
  ('Staunton', 'staunton-va', 'VA'),
  ('Fairfax', 'fairfax-va', 'VA'),
  ('Reston', 'reston-va', 'VA'),
  ('Arlington', 'arlington-va', 'VA'),
  ('McLean', 'mclean-va', 'VA'),
  ('Tysons Corner', 'tysons-corner-va', 'VA'),
  ('Leesburg', 'leesburg-va', 'VA'),
  ('Blacksburg', 'blacksburg-va', 'VA'),
  ('Radford', 'radford-va', 'VA'),
  ('Waynesboro', 'waynesboro-va', 'VA'),
  ('Colonial Heights', 'colonial-heights-va', 'VA'),
  -- Washington
  ('Seattle', 'seattle-wa', 'WA'),
  ('Spokane', 'spokane-wa', 'WA'),
  ('Tacoma', 'tacoma-wa', 'WA'),
  ('Vancouver', 'vancouver-wa', 'WA'),
  ('Bellevue', 'bellevue-wa', 'WA'),
  ('Kent', 'kent-wa', 'WA'),
  ('Everett', 'everett-wa', 'WA'),
  ('Renton', 'renton-wa', 'WA'),
  ('Federal Way', 'federal-way-wa', 'WA'),
  ('Yakima', 'yakima-wa', 'WA'),
  ('Spokane Valley', 'spokane-valley-wa', 'WA'),
  ('Bellingham', 'bellingham-wa', 'WA'),
  ('Kennewick', 'kennewick-wa', 'WA'),
  ('Auburn', 'auburn-wa', 'WA'),
  ('Redmond', 'redmond-wa', 'WA'),
  ('Marysville', 'marysville-wa', 'WA'),
  ('Lakewood', 'lakewood-wa', 'WA'),
  ('Olympia', 'olympia-wa', 'WA'),
  ('Pullman', 'pullman-wa', 'WA'),
  ('Walla Walla', 'walla-walla-wa', 'WA'),
  -- West Virginia
  ('Charleston', 'charleston-wv', 'WV'),
  ('Huntington', 'huntington-wv', 'WV'),
  ('Morgantown', 'morgantown-wv', 'WV'),
  ('Parkersburg', 'parkersburg-wv', 'WV'),
  ('Wheeling', 'wheeling-wv', 'WV'),
  ('Weirton', 'weirton-wv', 'WV'),
  ('Fairmont', 'fairmont-wv', 'WV'),
  ('Martinsburg', 'martinsburg-wv', 'WV'),
  ('Beckley', 'beckley-wv', 'WV'),
  ('Clarksburg', 'clarksburg-wv', 'WV'),
  ('Bluefield', 'bluefield-wv', 'WV'),
  ('St. Albans', 'st-albans-wv', 'WV'),
  ('Vienna', 'vienna-wv', 'WV'),
  ('South Charleston', 'south-charleston-wv', 'WV'),
  ('Dunbar', 'dunbar-wv', 'WV'),
  ('Moundsville', 'moundsville-wv', 'WV'),
  -- Wisconsin
  ('Milwaukee', 'milwaukee-wi', 'WI'),
  ('Madison', 'madison-wi', 'WI'),
  ('Green Bay', 'green-bay-wi', 'WI'),
  ('Kenosha', 'kenosha-wi', 'WI'),
  ('Racine', 'racine-wi', 'WI'),
  ('Appleton', 'appleton-wi', 'WI'),
  ('Waukesha', 'waukesha-wi', 'WI'),
  ('Eau Claire', 'eau-claire-wi', 'WI'),
  ('Oshkosh', 'oshkosh-wi', 'WI'),
  ('Janesville', 'janesville-wi', 'WI'),
  ('West Allis', 'west-allis-wi', 'WI'),
  ('La Crosse', 'la-crosse-wi', 'WI'),
  ('Sheboygan', 'sheboygan-wi', 'WI'),
  ('Wausau', 'wausau-wi', 'WI'),
  ('Fond du Lac', 'fond-du-lac-wi', 'WI'),
  ('New Berlin', 'new-berlin-wi', 'WI'),
  ('Wauwatosa', 'wauwatosa-wi', 'WI'),
  ('Brookfield', 'brookfield-wi', 'WI'),
  ('Manitowoc', 'manitowoc-wi', 'WI'),
  ('Stevens Point', 'stevens-point-wi', 'WI'),
  -- Wyoming
  ('Cheyenne', 'cheyenne-wy', 'WY'),
  ('Casper', 'casper-wy', 'WY'),
  ('Laramie', 'laramie-wy', 'WY'),
  ('Gillette', 'gillette-wy', 'WY'),
  ('Rock Springs', 'rock-springs-wy', 'WY'),
  ('Sheridan', 'sheridan-wy', 'WY'),
  ('Jackson', 'jackson-wy', 'WY'),
  ('Cody', 'cody-wy', 'WY'),
  ('Rawlins', 'rawlins-wy', 'WY'),
  ('Riverton', 'riverton-wy', 'WY'),
  ('Evanston', 'evanston-wy', 'WY'),
  ('Powell', 'powell-wy', 'WY'),
  ('Worland', 'worland-wy', 'WY'),
  ('Lander', 'lander-wy', 'WY')
) AS v(name, slug, state)
LEFT JOIN metros m ON m.name = CASE
  -- Map known metros
  WHEN v.state = 'GA' AND v.name IN ('Atlanta','Sandy Springs','Roswell','Johns Creek','Alpharetta','Marietta','Smyrna','Kennesaw','Lawrenceville','Peachtree City','Douglasville','Snellville','Lilburn','Norcross','Duluth','Suwanee','Sugar Hill','Buford','Cumming','Conyers','Covington','Griffin','Morrow','Forest Park','College Park','East Point','Union City','Fairburn','Hiram','Villa Rica','Dallas','Acworth','Powder Springs','Canton','Woodstock','Cartersville','Newnan','Carrollton') THEN 'Atlanta Metro'
  WHEN v.state = 'GA' AND v.name IN ('Savannah','Hinesville','Statesboro','Brunswick','Vidalia','Waycross') THEN 'Savannah Metro'
  WHEN v.state = 'GA' AND v.name IN ('Augusta') THEN 'Augusta Metro'
  WHEN v.state = 'GA' AND v.name IN ('Athens') THEN 'Athens Metro'
  WHEN v.state = 'GA' AND v.name IN ('Macon','Warner Robins','Milledgeville','Dublin') THEN 'Macon Metro'
  WHEN v.state = 'GA' AND v.name IN ('Columbus','LaGrange') THEN 'Columbus Metro'
  WHEN v.state = 'GA' AND v.name IN ('Valdosta','Tifton','Thomasville','Moultrie','Fitzgerald') THEN 'Valdosta Metro'
  WHEN v.state = 'IL' AND v.name IN ('Chicago','Aurora','Naperville','Joliet','Elgin','Waukegan','Cicero','Evanston','Schaumburg','Buffalo Grove','Bolingbrook','Carol Stream','Oak Lawn','Tinley Park','Skokie','Des Plaines','Orland Park','Palatine','Oak Park','Wheaton','Glenview','Downers Grove','Mount Prospect','Plainfield','Romeoville','Hoffman Estates') THEN 'Chicago Metro'
  WHEN v.state = 'CA' AND v.name IN ('Los Angeles','Long Beach','Anaheim','Santa Ana','Irvine','Huntington Beach','Garden Grove','Fullerton','Costa Mesa','Orange','Downey','West Covina','Norwalk','Burbank','Glendale','Santa Clarita','Lancaster','Palmdale','Pomona') THEN 'Los Angeles Metro'
  WHEN v.state = 'CA' AND v.name IN ('San Francisco','Oakland','Fremont','San Jose','Sunnyvale','Santa Rosa','Concord','Berkeley','Richmond','Daly City','San Mateo','Vallejo','Fairfield','Antioch','Hayward') THEN 'Los Angeles Metro'
  WHEN v.state = 'TX' AND v.name IN ('Houston','Pasadena','Pearland','League City','Conroe','Missouri City','Sugar Land','Spring','Baytown','Texas City','Friendswood','Seabrook','Webster','La Porte','Deer Park','Galena Park','Jacinto City','Channelview','Cloverleaf','Humble','Katy','Cypress') THEN 'Houston Metro'
  WHEN v.state = 'TX' AND v.name IN ('Dallas','Fort Worth','Arlington','Plano','Garland','Irving','Frisco','McKinney','Grand Prairie','Mesquite','Denton','Lewisville','Richardson','Allen','Carrollton','Waco','McKinney','Rowlett','Cedar Hill','Coppell','DeSoto','Duncanville','Farmers Branch','Flower Mound','Grapevine','Haltom City','Hurst','Keller','Lancaster','Mansfield','North Richland Hills','Richland Hills','Roanoke','Southlake','Sachse','Watauga','Wylie','Bedford','Colleyville','Euless','Bedford','Trophy Club','Westlake','Azle','Saginaw','Eagle Mountain','White Settlement','Forest Hill','Everman','Crowley','Burleson','Joshua','Cleburne','Alvarado','Venus','Keene','Rio Vista','Godley','Lillian','Briaroaks','Covington','Grandview','Crescent','Bardwell','Ennis','Waxahachie','Midlothian','Red Oak','Glenn Heights','Ovilla','Hutchins','Wilmer','Seagoville','Combine','Crandall','Kaufman','Terrell','Talty','Forney','Sunnyvale','Balch Springs','Lavon','Nevada','Josephine','Royse City','Caddo Mills','Greenville','Commerce','Wolfe City','Quinlan','Hawk Cove','West Tawakoni','East Tawakoni','Wills Point','Canton','Edgewood','Van','Grand Saline','Emory','Point','Easton','Overton','Arp','Troup','Whitehouse','Bullard','Lake Jackson','Jacksonville','Rusk','Alto','Reklaw','Cushing','Nacogdoches','Lufkin','Hudson','Diboll','Burke','Huntington','Wells','Douglass','Mount Enterprise','Carlton','Goodrich','Leggett','Onalaska','Livingston','Coldspring','Shepherd','New Waverly','Huntsville','Trinity','Anderson','Bedias','Iola','North Zulch','Madisonville','Midway','Centerville','Leona','Buffalo','Oakwood','Fairfield','Teague','Freestone','Wortham','Kirvin','Donie','Streetman','Mexia','Coolidge','Groesbeck','Thornton','Kosse','Mart','McGregor','Leroy','Hillsboro','Hubbard','Penelope','Birome','Braham','Bynum','Itasca') THEN 'Dallas-Fort Worth Metro'
  WHEN v.state = 'TX' AND v.name IN ('Austin','Round Rock','Cedar Park','Georgetown','Pflugerville','San Marcos','Leander','Hutto','Taylor','Buda','Kyle','Bee Cave','Lakeway','West Lake Hills','Sunset Valley','Rollingwood','Jonestown','Lago Vista','Point Venture','Volente','Spicewood','Briarcliff','Lakeway','The Hills') THEN 'Austin Metro'
  WHEN v.state = 'TX' AND v.name IN ('San Antonio','New Braunfels','Schertz','Seguin','Universal City','Live Oak','Converse','Kirby','Windcrest','Terrell Hills','Olmos Park','Alamo Heights','Balcones Heights','Castle Hills','Hill Country Village','Hollywood Park','Shavano Park','Somerset','China Grove','Elmendorf','Lytle','Macdona','Von Ormy','Adkins','Saint Hedwig','La Vernia','Marion','Zuehl','Cibolo','Selma','Martinez','Santa Clara','McQueeney','Kingsbury','Seguin','Geronimo','New Braunfels','Gruene','Canyon Lake','Spring Branch','Bulverde','Timberwood Park','Sattler','Startex','Hancock','Fischer','Wimberley','San Marcos','Kyle','Buda','Lockhart','Luling','Martindale','Fentress','Niederwald','Uhland','Wells Branch','Pflugerville','Hutto','Taylor','Thrall','Coupland','Granger','Troy','Cameron','Rockdale','Lexington','Giddings','Dime Box','Fedora','Carmine','Round Top','Warrenton','Industry','New Ulm','Cat Spring','Sealy','Bellville','Wallis','San Felipe','Brookshire','Pattison','Katy','Brookside Village','Pearland','Alvin','Angleton','Clute','Lake Jackson','Richwood','Sweeny','West Columbia','Brazoria','Damon','Old Ocean','Wild Peach Village','Jones Creek','Quintana','Surfside Beach','Freeport','Clifton','Meridian','Iredell','Morgan','Walnut Springs','Kopperl','Lakeside Village','Bristol','Bland','Coolidge','Frost','Mertens','Navarro Mills','Rice','Emhouse','Powell','Purdon','Retreat','Blooming Grove','Barry','Corsicana','Dawson','Rice','Pursley','Oak Valley','Mustang','Oakwood','Wortham','Teague','Freestone','Kirvin','Donie','Streetman','Mexia','Coolidge','Groesbeck','Thornton','Kosse','Mart','McGregor','Leroy','West','Hillsboro','Hubbard','Penelope','Birome','Braham','Bynum','Itasca','Covington','Grandview','Venus','Alvarado','Lillian','Briaroaks','Crescent','Bardwell','Ennis','Waxahachie','Midlothian','Red Oak','Glenn Heights','Ovilla','DeSoto','Lancaster','Hutchins','Wilmer','Seagoville','Combine','Crandall','Kaufman','Terrell','Talty','Forney','Sunnyvale','Mesquite','Balch Springs','Garland','Rowlett','Sachse','Wylie','St. Paul','Lavon','Nevada','Josephine','Royse City','Caddo Mills','Greenville','Commerce','Wolfe City','Quinlan','Hawk Cove','West Tawakoni','East Tawakoni','Wills Point','Canton','Edgewood','Van','Grand Saline','Emory','Point','Easton','Overton','Arp','Troup','Whitehouse','Bullard','Lake Jackson','Jacksonville','Rusk','Alto','Reklaw','Cushing','Nacogdoches','Lufkin','Hudson','Diboll','Burke','Huntington','Wells','Douglass','Mount Enterprise','Carlton','Goodrich','Leggett','Onalaska','Livingston','Coldspring','Shepherd','New Waverly','Huntsville','Trinity','Anderson','Bedias','Iola','North Zulch','Madisonville','Midway','Centerville','Leona','Buffalo','Oakwood','Fairfield','Teague','Freestone','Wortham','Kirvin','Donie','Streetman','Mexia','Coolidge','Groesbeck','Thornton','Kosse','Mart','McGregor','Leroy','Hillsboro','Hubbard','Penelope','Birome','Braham','Bynum','Itasca') THEN 'San Antonio Metro'
  WHEN v.state = 'FL' AND v.name IN ('Miami','Hialeah','Fort Lauderdale','Pembroke Pines','Hollywood','Miramar','Coral Springs','Davie','Miami Gardens','Sunrise','Plantation','Boca Raton','Doral','Homestead','Tamarac','Delray Beach') THEN 'Miami Metro'
  WHEN v.state = 'FL' AND v.name IN ('Orlando','St. Cloud','Kissimmee') THEN 'Orlando Metro'
  WHEN v.state = 'FL' AND v.name IN ('Tampa','St. Petersburg','Clearwater') THEN 'Tampa Metro'
  WHEN v.state = 'FL' AND v.name IN ('Jacksonville') THEN 'Jacksonville Metro'
  WHEN v.state = 'NY' AND v.name IN ('New York','Yonkers','New Rochelle','Mount Vernon','White Plains','Hempstead','Freeport','Valley Stream','Long Beach') THEN 'New York Metro'
  WHEN v.state = 'PA' AND v.name IN ('Philadelphia','Chester','Easton','Allentown','Bethlehem') THEN 'Philadelphia Metro'
  WHEN v.state = 'AZ' AND v.name IN ('Phoenix','Mesa','Chandler','Scottsdale','Glendale','Gilbert','Tempe','Peoria','Surprise','Goodyear','Buckeye','Avondale','Queen Creek') THEN 'Phoenix Metro'
  ELSE NULL
END
JOIN states s ON s.abbreviation = v.state
WHERE m.state_id = s.id OR m.id IS NULL
ON CONFLICT (slug) DO NOTHING;

-- ==================== REFRESH METRO PROGRESS ====================
SELECT refresh_metro_progress(metro_id) FROM (SELECT DISTINCT metro_id FROM cities WHERE metro_id IS NOT NULL) t;